- app.go
- build.sh
- schema.go
This helps with images which are part of the stack but are not built or do not need to be rebuilt by the faas-cli at this time.
> Add -skipBuild flag for non-built images

- app.go
Main Change:
Created a copyTree function to address [issue#18](https://github.com/alexellis/faas-cli/issues/18).
The function takes a similar approach to copyFiles but on finding a folder creates an equivalent folder in the build dir and then calls itself, this time passing in the source folder and newly created target folder.  This means that all files and folder to _n-levels_ will be copied.
A helper function has also been created; `pathExists()` is used within `copyTree` to try to offset errors where the destination may already exist.
Finally, replaced the two `copyFile` calls for the template folders with a single call to `copyTree` and amended the TODO comment accordingly. 
Test:
Created 10 levels of files and folders beneath a …
> Added copyTree function and replaced the template copyFiles calls

- app.go
Added a -squash flag to address  #23.
Fixed issue where supplying -no-cache flag would cause builds to fail
Changed http_proxy test to include a test for https_proxy (typo in the OR)
Refactored the generation of the build string to alleviate need for multiple operations in a proxy environment.... Previously the `builder` var would be initialised once outside the proxy test and then reassigned within the proxy test with additional params.  By buffering the docker build flags throughout the flag checks we can then just initialise `builder` once post-checks with code as succinct as the original initialisation.
**EDIT** Added a function `buildFlagString` to build the build flags string, as suggested.
**Pre:**
On Master ran `./faas-cli -action …
> Added squash flag & associated fixes

- README.md
This PR updates the Brew Formula update steps to include the `bump-formula-pr` command for use with simple version bumps.
Its expected that the bulk of updates should not require manual PRs to be raised against Brew, the `bump-formula-pr` command offers a much simpler process and is usually approved more quickly by the upstream project.
This process was used for the recent `0.4.6` release.
> Add bump-formula-pr to Brew update steps

- get.sh
This PR updates the one-line installer `get.sh` to use the latest full release from Github rather than use a hard-coded version string.
Draft releases and prereleases are not returned by the endpoint used to determine the version.
Currently `get.sh` uses a hardcoded version, the script hosted on https://cli.openfaas.com pulls in an outdated version 0.4.5b
Tested on Linux (Alpine, Fedora, Ubuntu, CentOS), and OSX.
For example:
```
$ sudo ./get.sh
Password:
Getting package https://github.com/alexellis/faas-cli/releases/download/0.4.7/faas-cli-darwin
Attemping to move faas-cli to /usr/local/bin
New version of faas-cli installed to /usr/local/bin
```
> Update get.sh to determine latest full release from Github

- app.go
- template/csharp/Dockerfile
- template/node-armhf/Dockerfile
- template/node/Dockerfile
- template/python-armhf/Dockerfile
- template/python/Dockerfile
- template/ruby/Dockerfile
> Update fwatchdog to 0.6.1 and correct help message for "action" option

- builder/build.go
- commands/build.go
Addresses issue #59.  
Changes the recursive arg to true on the handler `copyFiles` call so that sub directories within the handler are also copied into the build directory. 
Extracted a `debugPrint` function to avoid code repetition as The new directory branch in `copyFiles` now messages out only if the system is creating a new directory and `debug` is enabled.
Corrected a typo which meant that `err` was being tested rather than `newDirErr` when a new directory is being created.
Changed FaaS to OpenFaaS where seen.
#59
Created 10 levels of files and folders beneath a handler folder
Ran ./faas-cli -action build -yaml ./samples.yml
Confirmed that the images built successfully.
Confirmed that the expected files and folders were extant in the …
> Added recusion to handler copy + debugPrint fn

- .travis.yml
- Dockerfile
- Dockerfile.redist
- test/version.sh
This PR fixes the importpath to fully identify the `commands` package so that the GitCommit var can be populated at build time. The associated issue was raised in #62 and originally spotted by @ems5311 - thanks!!
This will fix binaries build by the `build_redist.sh` script, with the Brew built release requiring the same update in the homebrew-core formula (ie bumping the version on the command line isn't sufficient this time).
- Built manually passing in the version ldflag option and then ran `./faas-cli version`
- Built all the platform variants via `build_redist.sh` and then ran `./faas-cli version` on MacOS and Ubuntu
- In both cases above the GitCommit was populated as expected.
```
root@ff2edcc0885b:/# /faas/faas-cli version
Git Commit: b877c56f07d5b0ab6c417cb9eeeb06126e58031a
```
> Fix importpath in Go linker -X ldflag - fixes #62

- commands/invoke.go
- commands/list.go
- commands/new_function.go
- proxy/delete.go
- proxy/deploy.go
- proxy/invoke.go
- proxy/list.go
- sample/url-ping/handler.py
This PR includes a number of minor fixes to issues found when reviewing the new `faas-cli` subcommands - `invoke`, `list`, `new`.
Please see the individual commits (1 per issue) for more details on each issue.
- Fixes capitalisation in `invoke` help
- Fix handling for gateway URLs, removing trailing `\`
- Fix `url-ping` function so that it works when used with `invoke`
- Suppress `Reading from STDIN..` message when STDIN is piped to the `invoke`
- Fix handling of the default Gateway URL in the `invoke` command
- Fix help text in the `new` function command
Tested locally on a swarm instance, details of the tested commands are given in each commit.jj
> Assorted minor fixes while testing new faas-cli subcommands

- proxy/deploy.go
- template/csharp/Dockerfile
Signed-off-by: Robbie Page <rob@rorpage.com>
I have updated the csharp template to use multi-stage. The first stage is using the dotnet SDK, and the second uses the runtime.
The dotnet images are rather large so by implementing a multi-stage build, we decrease the end function image.
[#53](https://github.com/alexellis/faas-cli/issues/53)
I updated my template locally, created a new csharp function, built, deployed, and invoked the function and saw that everything ran as expected.
> [WIP] Use multi-stage build for CSharp

- .travis.yml
- Dockerfile
- Dockerfile.redist
- build.sh
- build_redist.sh
- stack/stack.go
- stack/stack_test.go
* `gofmt` to break local and CI builds 
Build changes
> Make gofmt fail builds

- commands/deploy.go
- commands/faas.go
- proxy/deploy.go
Add ```--network``` flag to deploy command in order to override the network name
> Allow to override the network name from CLI

- .gitignore
- .travis.yml
- Dockerfile.redist
- build_redist.sh
Support ARM64 for Packet
Packet have enterprise ARM64 servers available for testing and want to show OpenFaaS running at scale on ARM hardware. This provides a binary for the CLI and a template for Node.js.
Provision a Type2A at Packet.net - or use a SoC like a Pine64
Dockerfile for Node.js available in ./template/node-arm64
There is no official Node-Alpine image yet so this uses Debian instead as a base.
> Support ARM64 for Packet

- commands/build.go
- commands/fetch_templates.go
- commands/fetch_templates_test.go
- commands/new_function.go
This change will remove the master.zip file after the `fetchTemplates()` function is done creating the templates from the downloaded zip file.
Use the `os.Remove()` function to remove the zip file, whose name is now stored in a const variable, after making sure that the zip file is still present with `os.Stat()`
Noticed the zip file hanging around, was confused as to its necessity to remain the directory. However, as long as the `templates` directory is present in your YAML build file location, the `master.zip` file will not be used. Therefore, it is not necessary to keep it around.
Tried building the node, python, csharp, ruby, and Dockerfile templates, and checked that the master.zip file was removed, but the function worked when deployed.
> Remove master.zip file after building function with faas-cli build

- CONTRIBUTING.md
Signed-off-by: Ian Philpot <ian.philpot@microsoft.com>
updated contrib docs
changed ...$GOPATH/src/github.com/alexellis/
to ...$GOPATH/src/github.com/openfaas/
no issues raised
markdown looks good
docs
yes
> Updated contributing.md with new openfaas path

- commands/deploy.go
- proxy/deploy.go
This PR is part of a group of 3:
- openfaas/faas#208
- openfaas/faas-cli#123
- openfaas/faas-provider#4
This commit switches the verb used for updates from the non-HTTP UPDATE to PUT.
It also updates the message returned from the deploy action depending on whether its a deploy or update:
```
$ ./faas-cli-darwin deploy -f ./samples.yml --replace=false --update
Updating: ruby-echo.
Updated.
URL: http://localhost:8080/function/ruby-echo
```
UPDATE is not a valid HTTP verb, the correct verb to use for updates is PUT (as pointed out by @imeoer - thx!)
Tested performing a range of updates on a local swarm, changing envvars etc.
> Use PUT verb for function updates and update messages

- stack/stack.go
- stack/stack_test.go
Print error message when no matches are found by --filter or --regex flag
This change is to return an error message when all functions are filtered out by the --filter or --regex option. The current error message is `"No functions found in YAML, check --filter/--regex"`.
Issue #124 
This will help users figure out what is wrong with their command if they expect functions to be deployed, and nothing happens.
Tests were upgraded to accommodate this change and check for this error to be properly thrown when --filter and --regex remove all functions.
> Print error message when no matches are found by --filter or --regex flag

- builder/exec.go
faas-cli will now check the exit status of exec commands
(i.e. <docker build ...>) and will "stop the world" if
a non-zero exit occurs.
Signed-off-by: Alex Shorsher <alex.shorsher@gmail.com>
Previously, even if `faas-cli build` failed when building a container from a Dockerfile, faas-cli would continue executing.  The correct behavior should be to stop faas-cli execution, log, and present the user with a noticeable error message.  
The issue originally just referenced throwing an error if `faas-cli build` fails, however, it seems my changes would also add error checking for other commands that use ExecuteCommand() (currently just `faas-cli push`).  I think this is acceptable?
#138 
Here are some gif's of me running tests using the included samples.  They include a single function building …
> Error checking for cli exec-commands

- Dockerfile
- Makefile
- builder/build.go
- commands/new_function.go
- template/go/Dockerfile
- template/go/function/handler.go
- template/go/function/handler_test.go
- template/go/main.go
Added capability to create functions in go, a new template has been added and the cli has been modified to allow an additional language 'Go'.
This update adds the capability to create new functions using the Go programming language using the fans-cli.
https://github.com/openfaas/faas-cli/issues/86
Unit tests have been run and a manual test has been performed creating a Go function and deploying it to OpenFaaS.  The function was then load tested on the running OpenFaaS instance.
> Add Go template capability for creating functions

- template/go/Dockerfile
Changes step 6 of the golang template Dockerfile so that `go test` ignores the vendor directory.
Fixes #146 
Pre-Testing
```
Step 6/17 : RUN CGO_ENABLED=0 GOOS=linux     go build --ldflags "-s -w" -a -installsuffix cgo -o handler . &&     go test ./... -cover
---> Running in 1e4f120fde05
?   	handler	[no test files]
ok  	handler/function	0.003s	coverage: 80.0% of statements
ok  	handler/function/vendor/github.com/cnf/structhash	0.003s	coverage: 88.4% of statements
---> f8ec69fde5ce
```
Post-Testing
```
Step 6/17 : RUN CGO_ENABLED=0 GOOS=linux     go build --ldflags "-s -w" -a -installsuffix cgo -o handler . &&     go test $(go list ./... | grep -v /vendor/) -cover
---> Running in 43b6eb844b50
?   	handler	[no test files]
ok …
```
> Amend golang template Dockerfile so that go test ignores vendor fixes #146

- README.md
Signed-off-by: Finnian Anderson <get@finnian.io>
In the README, there is an example for the `environment_file` which has the incorrect syntax for the yaml.
This:
```yaml
environment:
- access_key: key1
- secret_key: key2
```
Should be this:
```yaml
environment:
access_key: key1
secret_key: key2
```
I've also added a couple of missing `yaml` code block syntax highlighting labels.
Misleading example, had to battle with it for 10 minutes so I thought it would be nice to update the example so others don't encounter the same issue.
> Fix environment file example

- vendor.conf
Signed-off-by: John McCabe <john@johnmccabe.net>
Looks like `vendor.conf` hadn't been updated when the `aec` and `inconshreveable` deps were added.
This commit freezes the deps in `vendor.conf` without altering any of the vendored versions.
Skipped due to trivial nature of the change.
> Add missing deps to vendor.conf

- commands/deploy.go
if you have a non-default gateway in YAML the --gateway flag is ignored if passed as an override.
Bug fix.
Use YAML with a non-default gateway and pass --gateway.
> Fixes --gateway override which was ignored when using YAML

- README.md
- commands/deploy.go
- proxy/deploy.go
- proxy/deploy_test.go
- stack/schema.go
- vendor/github.com/openfaas/faas/gateway/requests/requests.go
Adds label support for functions
Needed for https://github.com/openfaas/faas/pull/325
Tested with https://github.com/openfaas/faas/pull/325 - via:
* YAML
* YAML plus arguments --label
* Via arguments only --label
This change has a back-end fix with swarm, but Kubernetes support will come in a follow-up PR.
> Add label support

- commands/fetch_templates.go
- proxy/deploy.go
- proxy/invoke.go
- proxy/list.go
- proxy/proxy.go
- stack/stack.go
Add timeouts for HTTP clients
The configuration of IPv4 / IPv6 and Docker on Linux can be confusing - i.e. #164 
This PR should stop "infinite" hang by setting an explicit 3 second timeout.
This timeout is likely to need to be extended for "invoke" or it could break long-running functions.
```
pi@swarm1:~ $ cat /etc/hosts
127.0.0.1	localhost
::1		localhost ip6-localhost ip6-loopback
ff02::1		ip6-allnodes
ff02::2		ip6-allrouters
127.0.1.1	swarm1
pi@swarm1:~ $ ./faas-cli-armhf list
Get http://localhost:8080/system/functions: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
2017/10/14 12:09:02 cannot connect to OpenFaaS on URL: http://localhost:8080
pi@swarm1:~ $ 
```
> Add timeouts for HTTP clients

- MANUAL_CLI.md
- commands/build.go
- commands/deploy.go
- commands/invoke.go
- commands/list.go
This PR stops using `node` as a default language due to it conflicting with functions where the `fprocess`envvar  is set in the image.
Given the large numbers of languages having a default makes less sense now.
It also removes some of the copy-paste/redundant/irrelevant flag definitions that ended up in newly added subcommands.
1. Have run deploy, build, invoke and list commands without problem.
2. Run a deploy with no `--fprocess` flag, function gets created with one being set as expected and correctly honours the setting in the image.
3. Ran a build with --lang set and successfully built and deployed (used the [first-faas-python-function](https://blog.alexellis.io/first-faas-python-function/) guide as a test run).
Strictly speaking this *is* a breaking change, but it only impacts a very …
> Remove language default and fix command flags

- template/node/Dockerfile
Initial draft of non-root user in the NodeJS template.
update the template/node/Dockerfile to use the `node` user rather than root. function directory structure needed to changed from `/root/` to `/usr/local/app/` as well 
Allows users to run function as non-root which may increase security
This relates to #81 
already raised by @alex #81 
Manually built test function after changes, deployed and tested through the UI gateway
Linux 16+ on Docker CE 17.06
Will only impact the NodeJS template
> [WIP] non-root user for NodeJS template

- commands/build.go
- commands/build_test.go
- commands/faas.go
Resolves the issue: #183
```
$ ./faas-cli build
Error: please provide a valid -image name for your Docker image
$ echo $?
1
```
> Enable non-zero-exit in case of an error while running "build"

- proxy/delete.go
- proxy/delete_test.go
- proxy/deploy.go
- proxy/deploy_test.go
- proxy/invoke.go
- proxy/invoke_test.go
- proxy/list.go
- proxy/list_test.go
This change is to add error handling for the `http.NewRequest()` call in the `list`, `deploy`, `delete`, and `invoke` files.
https://github.com/openfaas/faas-cli/blob/46b2db894024f8707d080510202a592930894d9e/proxy/list.go#L26
Currently if an error occurs here, the error variable is thrown out, and we call `client.Do()` with a `nil` parameter.
Handle the error each time `http.NewRequest()` is used, and return it to the user.
Got a runtime error when I put in an incorrectly formatted URL. Issue: #185
> Add error handling for calls to http.NewRequest() in package proxy

- proxy/delete_test.go
- proxy/deploy_test.go
- proxy/invoke_test.go
- proxy/list_test.go
This change is to add better testing for the changes recently merged from PR #198, as per the changes requested by Alex.
The reqeusted changes:
1. Error handling should use want/go syntax, for clearer error messages.
2. More descriptive function name is needed
Updated these tests to use a better name (`MissingURLPrefix` rather than `BadURL`) and use want/go error reporting syntax.
#185 
On build all tests pass.
> Update tests for invalid --gateway URL to use got/want in error message

- .gitignore
- README.md
- commands/login.go
- commands/logout.go
- config/file.go
- config/file_test.go
- proxy/auth.go
- proxy/auth_test.go
- proxy/delete.go
- proxy/delete_test.go
- proxy/deploy.go
- proxy/deploy_test.go
- proxy/invoke.go
- proxy/invoke_test.go
- proxy/list.go
- proxy/list_test.go
- vendor.conf
- vendor/github.com/mitchellh/go-homedir/LICENSE
- vendor/github.com/mitchellh/go-homedir/README.md
- vendor/github.com/mitchellh/go-homedir/homedir.go
This PR adds a new command named `login` that allows users to register multiple gateways protected with basic auth. The credentials are being saved to `$HOME/.openfaas/config.yml` on Linux/macOS and `%USERPROFILE%/.openfaas/config.yml` on Windows. The `yml` extension is used to avoid overriding the openfaas-bitbar `config.yaml`. 
CLI `login` command specs:
* validates the credentials by calling `list` for a given gateway
* issues a warning if the password is passed via command line and advise on using stdin
* issues a warning if the gateway is not on HTTPS and advise on using Letsencrypt
* creates or updates credentials for a given gateway
* encodes the username and password with base64 for local storage
* sets auth to `basic` type in the YAML auth store
Upon calling a gateway API …
> [Testing] Support Basic Auth for multiple gateways

- README.md
- commands/faas.go
- commands/faas_test.go
- commands/testdata/stack.yml
Added capability to load a default configuration file `stack.yaml` when present in the current folder.  If a default is present this can still be overridden by providing the flag `--yaml=file.yaml`
Code has been tested on a unit level and basic manual testing has also been performed.
> Default to stack.yml when no --yaml flag given

- commands/new_function.go
- commands/update_gitignore.go
- commands/update_gitignore_test.go
> Update .gitignore when generating templates

- commands/deploy.go
Don't re-use constraints for each function
Fixes #218 
Via CLI
```
var functionConstraints []string
if function.Constraints != nil {
functionConstraints = *function.Constraints
} else if len(constraints) > 0 {
functionConstraints = constraints
}
```
Constraints are empty unless they are found in the YAML, unless they are found in argument parameters.
> Don't re-use constraints for each function

- template/node/.dockerignore
- template/node/Dockerfile
Signed-off-by: Nic Jackson <jackson.nic@gmail.com>
When building a node function any existing node_modules present in the function folder would be copied to the docker image and npm install would not happen causing permissions errors when running Docker on Linux.
Updated the Dockerfile to fix an issue where the npm install took place and the functions folder was copied over the top.
Added a .dockerignore file to ignore node modules.
Tested locally and and also against a cluster running in AWS
> Updated build for node to fix issue with node_modules

- commands/bash_completion.go
- commands/build.go
- commands/deploy.go
- commands/faas.go
- commands/fetch_templates.go
- commands/invoke.go
- commands/list.go
- commands/login.go
- commands/logout.go
- commands/new_function.go
- commands/new_function_test.go
- commands/push.go
- commands/remove.go
- commands/template_pull_test.go
- proxy/list.go
- proxy/list_test.go
Signed-off-by: Tommy Stigen Olsen <tommysolsen@gmail.com>
As discussed in #183, I have gone through the commands and made all of the cobra commands 
use RunE, returning errors which triggers os.Exit(1).
Refactors all cobra commands except version (which never generates errors). This lets all of the commands exit with status-code 1 if an error occurs.
I have also cleaned up some of the different ways each function handles failure to a standard `fmt.Println` and `return err` style to be consistent across the modules.
Since RunE will print any error it receives, i've suppressed them so the software doesnt repeat itself.
See #183 
Tested through compiling and running a few functions that failed.
> Refactoring Commands to exit with non-0 status codes on failure.

- get.sh
Added the creation of a symbolic link of `faas` which points to `faas-cli`
Fixes #233
Referenced in #130
Update to reflect current live script.
> Amended get.sh to include the creation of the faas alias

- template/node-arm64/Dockerfile
- template/node-arm64/build.sh
- template/node/Dockerfile
- template/node/build.sh
Upgraded templates to NodeJS 8.9.1LTS
Issue #212 
Created new NodeJS functions and verified that the new features in Node 8.9.1 are available in the function. Namely, the async/await
There are some breaking changes with this latest version of Node, however, this change only affects new functions that are created with the templates. Existing functions using the previous Node 6.x templates are still valid.
> Updated the NodeJS templates to use the latest LTS versions. Fixes #212

- template/node-arm64/index.js
- template/node-armhf/index.js
- template/node/index.js
Assist the node memory manager by indicating non-changing names with `const` keyword instead of `let`.
Fixes #240
Signed-off-by: Daniel Llewellyn <daniel@bowlhat.net>
> update node template with `const` keywords

- commands/fetch_templates.go
Change switches to use openfaas/templates instead of the CLI repo for OpenFaaS templates.
https://github.com/openfaas/templates/
We'll have to "dual-maintain" two repos until we think folks have upgraded to the next release i.e. 0.5.1
> Switch to external template repository

- builder/build.go
- builder/build_test.go
Signed-off-by: Ganessh Kumar R P <rpganesshkumar@gmail.com>
This is a fix to #253, where cp removes any execute permission on the file by using default `0660` on the destination file.
This commit reads the mode of the source file using `os.Stat(src)` and use the source file's permission on the destination file.  The destination file will have the same permission as the source file.
- ~~My change requires a change to the documentation.~~
- ~~I have updated the documentation accordingly.~~
- ~~I have added tests to cover my changes.~~
> while copying a file use file mode from the source file

- README.md
- get.sh
Fixes #247 Let utility script run as non-root
Users may be less comfortable running a remotely sourced script as root.  This change enables users to run the cli get script as a non-root user and instructs them as to the next steps to be performed in order to complete installation.
Ran with and without sudo, thus:
```
$ cd ~
$ cat /tmp/get.sh | sudo sh
You already have the faas-cli!
Overwriting in 1 seconds.. Press Control+C to cancel.
Downloading package https://github.com/openfaas/faas-cli/releases/download/0.5.0/faas-cli-darwin as /tmp/faas-cli
Download complete.
Running as root - Attemping to move faas-cli to /usr/local/bin
New version of faas-cli installed to /usr/local/bin
```
And
```
$ cd ~
$ cat /tmp/get.sh | sh
You already have the …
```
> Added the ability to run get.sh as non-root user

- commands/remove.go
fix #267
Tested on Docker Swarm 17.09.1-ce with faas-swarm https://github.com/openfaas/faas/pull/460
Direct override
```
./faas-cli remove func_markdown --gateway=http://<GCP-IP>:8080
Deleting: func_markdown.
Removing old function.
```
Stack override
```
./faas-cli deploy -f ./sample/hmac.yml --gateway=http://<GCP-IP>:8080
Deploying: hmac.
No existing function to remove
Deployed.
200 OK
./faas-cli remove -f ./sample/hmac.yml --gateway=http://<GCP-IP>:8080
Deleting: hmac.
Removing old function.
```
> Fix gateway overriding for faas-cli remove

- proxy/deploy.go
- stack/schema.go
Added CPU limits for deployments
Added capability to pass CPU based constraint with a stackfile
[https://github.com/openfaas/faas-cli/issues/250](https://github.com/openfaas/faas-cli/issues/250)
The stack schema has been changed adding yaml struct tags and also the deployment proxy has been modified to pass the CPU based constraint.
CPU and memory based constraints should be possible
Tested with local build and deployment to k8s
> Added CPU limits for deployments

- commands/deploy.go
- commands/deploy_test.go
- proxy/deploy.go
- proxy/deploy_test.go
This change is to perform in-place update of functions rather than delete/create when the function already exists.
If the function does not already exist and we get 404, create the function.
#256 
Testing is improved in `proxy/deploy_test.go` by adding scaffolding with array-of-struct test cases.
We need to improve testing in this area by adding more test cases (hence why this is WIP).
> [WIP] Use rolling update instead of delete/create when function exists

- commands/deploy.go
- proxy/deploy.go
The purpose of this PR is to make the output for `faas-cli deploy` more clear when a rolling update is triggered, or when a rolling update fails and a regular 'create' deploy is triggered.
The output now looks like:
Function already exists:
```
$ faas-cli deploy --name echo --image functions/faas-echo:latest --gateway $gw
Function echo already exists, attempting rolling-update.
Deployed (updated)
URL: http://192.168.99.100:8080/function/echo
200 OK
```
Function does not yet exist:
```
$ faas-cli deploy --name echo --image functions/faas-echo:latest --gateway $gw
Function not found, attempting deployment.
Deployed
URL: http://192.168.99.100:8080/function/echo
200 OK
```
This change was proposed by Alex here: …
> Improve output for rolling updates

- commands/list.go
Adds shortvar of `-v` for `faas-cli list --verbose`
On Linux with remote cluster:
```
faas list
faas list -v
faas list --verbose
```
All work as expected
> Fixes #269 - allow shortvar for faas-cli list --verbose

- commands/deploy.go
- commands/login.go
fix #279
This PR allows the gateway URL to be specified in the `IP:PORT` format without HTTP/S.
If a protocol is not specified then HTTP will be used.
Tested on GKE with HTTP, HTTPS and IP:PORT
Before the fix:
```
./faas-cli login -u test -p test --gateway=163.172.143.209:31112
Calling the OpenFaaS server to validate the credentials...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x12de642]
```
After the fix:
```
./faas-cli login -u test -p test --gateway=163.172.143.209:31112
Calling the OpenFaaS server to validate the credentials...
Cannot connect to OpenFaaS on URL: http://163.172.143.209:31112
```
> Append http prefix to the gateway URL

- commands/deploy.go
Updated the help text for deploy around the `--update` and `--replace` flags to help avoid confusion. This came up as a question in the Slack contributors channel by Vivek
Added a note to the error messaging indicating that either the update or replace flag needs to be set to false
Also updated the `--help` text to indicate that `--update` was default to true to make it clearer
- No github issue, but mentioned in Slack channel as an improvement
> [WIP]Updated help and error text for deploy

- commands/template_pull.go
- commands/template_pull_test.go
Update the git url regex used in the `template pull` command to allow repo urls that do not have a `.git` suffix
Fixes #292 
Via unit tests, locally.
> Fix bug to allow plain urls for git repos

- commands/store.go
- schema/store_item.go
Fix parse env vars & add labels for store deploy command
```
"Labels": {
"com.openfaas.function": "colorise",
"com.openfaas.ui.ext": "png",
"function": "true"
},
```
> Fix parse env vars & add labels for store deploy command

- commands/new_function.go
- commands/new_function_test.go
This is a change to address the `Dockerfile` issue pointed out by issue #317 
This is a minimal fix which adds error handling around the `builder.CopyFiles()` call in `commands/new_function.go`. This PR was written with TDD as the tests were written first, then the minimal change was applied to get the tests to turn green.
#317 
Tests in `new_function_test.go` are expanded to cover lowercase as well as uppercase usage of `Dockerfile`.
> fix uppercase bug for Dockerfile template

- .gitmodules
- commands/new_function_test.go
- commands/testdata/templates/template/dockerfile/function/Dockerfile
- commands/testdata/templates/template/dockerfile/template.yml
- commands/testdata/templates/template/ruby/Dockerfile
- commands/testdata/templates/template/ruby/Gemfile
- commands/testdata/templates/template/ruby/function/Gemfile
- commands/testdata/templates/template/ruby/function/handler.rb
- commands/testdata/templates/template/ruby/index.rb
- commands/testdata/templates/template/ruby/template.yml
Introduced by #275
closes #299 
git submodule is removed, 2 test templates are added to the `testdata` dir: ruby & dockerfile
The test directory is copied to a temporary directory then git init is called to setup a local repo which will be used during tests
> Remove submodule in testdata

- builder/build.go
Currently, when the handler path is not valid, build passes with the `function` directory coming from template, we need to validate the handler path so that the build will stop if the function path is not correct.
Should I raise an issue?
> ensure that the handler path is valid before building

- commands/push.go
Added a check before calling `docker push` to ensure that the `image` field in the `.yml` file contains a repository by looking for `/`.
Added new function to `push.go` to validate that the image contains a repository by looking for `/` in the image string
Added output message with list of failed function names with message to indicate the failure (and an example of the correct usage)
I also moved the `"Pushing function1 done"` message into the else block that calls the `docker push` command. I thought it confusing to have that message show when the `push` never actually happened...
Closes #329 
Built the CLI locally and ran `./faas-cli push -f test.yml` with 3 functions defined. One with a repository `burtonr/movies:0.2`, one with …
> Check for username, ip, or registry on faas push

- commands/invoke.go
- proxy/invoke.go
- proxy/invoke_test.go
Fixes https://github.com/openfaas/faas-cli/issues/333
It is required to add --header or -H flag to pass headers as key=value for invoke command.
> [Ready to merge] implement --header -H flag for faas-cli invoke

- MANUAL_CLI.md
- README.md
- commands/config_priority_test.go
- commands/config_priorty.go
- commands/deploy.go
- commands/deploy_test.go
- commands/faas.go
- commands/invoke.go
- commands/list.go
- commands/login.go
- commands/remove.go
- commands/store_deploy.go
- commands/validate_test.go
- deploy_samples.sh
- sample/hmac.yml
- stack.yml
- stack/stack_test.go
* Adds `OPENFAAS_URL` env-var for gateway
* Moves to `127.0.0.1` over `localhost` to enforce IPv4 default and avoid clashes with systems that use IPv6 and hang when accessing `localhost` from Go
Signed-off-by: Alex Ellis (VMware) alexellis2@gmail.com <alexellis2@gmail.com>
This change fixes #345 
* Tested with override at env-var level
* Tested with YAML override
* Unit tests added
> OPENFAAS_URL env-var for gateway and IPv4 defaults

- commands/store_deploy.go
This change adds a call to getGatewayURL immediately prior to heading into deploy image.
The recently added feature to draw the gateway from an ENV var to save users having to repeatedly use -g was missed from the store's deploy feature.  This meant that even if the ENV var was set the CLI would still try to use the default.
- Existing unit tests pass.
- Post-Build testing:
Use local binary:
```
$ chmod +x faas-cli-darwin
```
No argument passed & OPENFAAS_URL not set.  Expect to use defaultGateway:
```
$ ./faas-cli-darwin store deploy figlet
Function figlet already exists, attempting rolling-update.
Deployed. 200 OK.
URL: http://127.0.0.1:8080/function/figlet
```
Invalid argument passed & OPENFAAS_URL not set.  Expect to use argument & fail …
> Add OPENFAAS_URL to store_deploy

- commands/deploy.go
- commands/faas.go
A recent change to faas-swarm means that if a network value isn't provided then the provider will try to ascertain the target network by looking for a label of openfaas=true within the network meta data.
This change will set the CLI defaultNetwork value to blank so that users who have not used the default network name will still attain desirable results when using the store & will no longer have to provide a network over-ride from the CLI.
**This is a breaking change and requires 0.7.3 or greater of the gateway.**
With the changes in openfaas/faas-swarm@e36f90b a default network is no longer required. Instead the network to be used will default to the swarm network labelled with openfaas during deployment.
Started with a clean server
Edited …
> Set defaultNetwork to empty value

- .gitignore
- builder/build.go
- commands/build.go
- commands/build_test.go
Enables build-flag to be passed through to the Docker CLI for
use with secrets or build-time configuration.
Fixes #363 and referenced issues.
Tested with plain Dockerfile template and adding an argument in
to be written to a file during a read-stage. That successfully
was captured in a file and read back at run-time showing the
change works. I also added validation for empty k/v or a lack of
separator (=).
Also tested with scenario quoted in issue. Existing tests pass.
> Add build-arg flag to build command

- .github/ISSUE_TEMPLATE.md
Changes to the issue template to request output from `faas-cli version`
Its a need to know detail.  Asking up-front saves a feedback cycle.
Its an issue template change
> Add faas-cli version information into Your Environment section

- get.sh
The quick-install script should throw an error if it doesn't successfully get the latest version of `faas-cli` available. This can be caused by Github API's [rate limiter](https://developer.github.com/v3/#rate-limiting).
https://github.com/openfaas/faas-cli/issues/377
Checked that the `if` statement works correctly when the `$version` variable is null.
> Exit+throw error on version not found in get.sh

- stack/language_template.go
Added a lowercase conversion within `IsValidTemplate()` so that `BuildImage()` can still enter into the top section of `if stack.IsValidTemplate(language)` when an uppercase Dockerfile is used in the yaml definition.
Previously changes were made to accommodate `Dockerfile` and `dockerfile` as languages.  One case overlooked was where `Dockerfile` is specified in the yaml definition.  This may occur where a user has a pre-existing yam file.
Small change tested in the community by @viveksyngh
> Fix yaml case sensitivity around Dockerfile templates

- commands/new_function.go
- commands/new_function_test.go
Makes sure new function names are valid to RFC-1123 DNS names [0]
This is to ensure that functions created can be built and
deployed on Kubernetes and Docker Swarm.
s8sg originally started this work in PR #375
[0] k8s.io/kubernetes/pkg/util/validation/validation.go
Closes #374
Tested with unit test coverage via @s8sg and through a local build:
```
$ go build && ./faas-cli new --lang go Alex
Function name can only contain a-z, 0-9 and dashes
```
Also tested with a positive test of `alex` as the function name.
This change further restricts function names to be compatible with Kubernetes as a default which will not allow `-` characters. This will not cause breakage since it only affects new functions but should be back-ported to the …
> Validate new function names

- README.md
- commands/deploy.go
Introduces flag --send-registry-auth due to concerns raised about
enabling this user-experience by default. 
See also: #386 and #387
which explains why we do not want to send credentials by default.
Tested with unit tests and local build of the CLI with a remote
Linux host on a MacOS client system.
Closes #387 
Closes #386
> Make registryAuth sending optional

- commands/deploy.go
- commands/new_function_test.go
- commands/store_deploy.go
- proxy/list_test.go
Moved Docker config into the section of code where it is first
used to prevent loading when not required.
Updated bad usage of println/printf which create build errors
when running in Go 1.10 and newer.
Closes #396 via Vivek Syngh
* `faas-cli-deploy`
For a negative test I pushed functions/alpine:latest as a new tag to a private Docker Hub repo then removed the image locally. Next I deployed without auth and saw that the service in Swarm was not scheduled.
For a positive test I passed the --send-registry-auth flag which allowed the function to be deployed.
* `faas store deploy`
I tested the default case to make sure it didn't send auth.
> PR code review 396

- builder/build.go
- builder/build_test.go
With the recent addition of --build-arg no provision for the potential for spaces
was made.  This was a problem as the slice that is passed into exec.command() was being
generated via a strings.Split() on space which meant values with spaces were split
across slice elements.
This change alters this behaviour by returning a slice of strings from the buildFlag function
which obviates the need for string.Split further downstream and so removes the potential for
mis-handling of spaces.
Much of the testing so far was performed through debugging the issue.
Added a test for the changed method `buildFlagSlice`
* Export a variable containing a private key
* Amend the relevant template Dockerfile to accept an `ARG` and add `ARG …
> [WIP] Accomodate spaces in --build-arg value

- get.sh
Currently the rate limiting condition in the get.sh script only works with `bash`. This simple fix updates it to improve compatibility with other shells such as `sh`.
Use a single `[` if statement rather than `[[`. In this case, there is no advantage to the double-square bracket anyway.
https://github.com/openfaas/faas-cli/issues/377
Manually tested by hitting the rate limit, and making sure that the proper message gets printed when the `$version` variable is missing.
> Fix get.sh to work with sh

- .gitignore
- README.md
- commands/cloud.go
- schema/secret.go
Add `cloud` sub-command for sealing secrets
Adds new command to seal a secret for use in OpenFaaS Cloud with
new subcommand "cloud". A sealed secret can be pushed into a
public Git repo without others being able to decrypt it.
The `kubeseal` CLI provides the implementation of the sealing
via exec - this is much less code and bloat than vendoring since
the kubeseal client API includes the Kubernetes Go client.
https://github.com/openfaas/openfaas-cloud/issues/20
Command tested with SealedSecrets running on Kubernetes with
kubeadm and the faas-cli running on MacOS.
See README.md for usage and more instructions.
>  Add `cloud` sub-command for sealing secrets

- builder/build.go
- builder/build_test.go
- commands/build.go
- commands/build_test.go
- stack/schema.go
This change adds a `build-option` flag to `faas-cli build`,
e.g. `faas-cli  build  -f  stack.yml --build-option=dev`.
If  the function  language  template  has  applied  `build_options` specification in its `template.yml` file, i.e.
```
build_options:
- name: dev
packages:
- musl-dev
- gcc
- make
```
then `ADDITIONAL_PACKAGE` agrument will be passed by `build-arg`.
This allows the listed packages to be built by the template's `Dockerfile` if it is edited to support the feature.
Signed-off-by: Ivana Yovcheva (VMware) <iyovcheva@vmware.com>
[templates/#28](https://github.com/openfaas/templates/issues/28)
1. Cloned @kenfdev's function from [kenfdev/faas-pandas-example](https://github.com/kenfdev/faas-pandas-example)
2. Changed python3 template with the changes from …
> Add support in templates for building native modules i.e. C/C++

- get.sh
A new function has been introduced called checkHash which checks that `shasum` is available on the system and if it does goes on to test the newly received binary against the checksum calculated at build time.  A sub-shell is invoked within this function as `shasum` needs to be called in the same dir as the binary and this location can vary depending on the user context.  Using a sub-shell means the directory switching is transparent to the user, who remains where they started regardless of the script outcome.
SHA256 checksum files were recently added to the releases page.  This change uses these in order to check the received binary.
Tested on MacOS, Ubuntu 18.04 & RPi3.
* MacOS:
```
$ sudo ./get.sh
You already have the faas-cli!
Overwriting in 1 seconds.. Press Control+C to cancel. …
```
> Add SHA checking to get.sh download script

- get.sh
This change defaults the command to be used to sha256sum and reverts to
shasum -a 256 if the default isnt found.
Also fixed a typo in the console output `attemping` --> `attempting`. 
The earlier choice of using shasum was made for broadest support reasons.  However
the breadth of support could be broader still by introducing graceful degradation
to get.sh.  
Small change.  Tested on MacOS and PWD (where the earlier script was failing) and verified that the command was correctly switching by adding a temporary echo `$sha_cmd`
* PWD
```
Running as root - Attemping to move faas-cli to /usr/local/bin
New version of faas-cli installed to /usr/local/bin
Creating alias 'faas' for 'faas-cli'.
/ _ \ …
```
> Add graceful degradation for sha_cmd in get.sh

- get.sh
This change replaces the -s option for shasum, which suppresses output, in favour of redirection to /dev/null.
As part of the graceful degradation change use of sha256sum was introduced.
On Ubuntu 16.04 the shorthand flag for status does not exist which results in
a failure when verifying the checksum.  Further, support for -s & the long --status flag
is inconsistent across distros. 
Pre-tested on Ubuntu 16.04 to validate reported issue
Post-tested on Ubuntu 16.04, MacOS and PWD to get a broad coverage of scenarios.
> Replace shorthand status flag with long verion in get.sh

- commands/version.go
If the gateway is not reachable when executing the version command do
not log a warning, this is expected behaviour and might be confusing
**Current behaviour before this PR, when no gateway is running**
```
|_|
CLI:
commit:  6c28891cf648621ef120c802d9160cae7506b977
version: 0.6.14
Warning could not contact gateway for version information on http://127.0.0.1:8080/system/info Get http://127.0.0.1:8080/system/info: dial tcp 127.0.0.1:8080: getsockopt: connection refused
```
**With this PR, Output when no gateway is running**
```
___                   _____ …
```
> Removes warning println in version command

- commands/deploy.go
- commands/deploy_test.go
This PR fixes the getRegistryAuth function so that it works correctly with images that exist in subdirs on custom docker registries, for example Gitlab.
Before this change the following image works as expected:
registry.gitlab.com/johnmccabe/myfunctions
But an image nested under that namespace would fail to find any auth from the docker cached creds, for example this would fail:
registry.gitlab.com/johnmccabe/myfunctions/coolfn
This fix address the underlying issue in the registry domain extraction so that both cases now work, I've tested with private registries on both Gitlab and Docker Hub successfully.
Have also added a test to catch the nested subdir image case.
Tested **on OSX** with private registry on both Gitlab (hosted), and Docker Hub.
> Fix registry auth for nested images in custom registry (Gitlab)

- commands/deploy.go
- commands/deploy_test.go
- commands/store_deploy.go
- proxy/deploy.go
This commit adds feature that lets faas-cli to exit
with code 1 when function exit with status 200 or 202
Extends faas-cli functionality to return proper exit status on codes that are 
different than 200 or 202
Extends deploy function to return status code and use that to determine
the exit status of the command 1 if the code is different than 200 or 202
It references https://github.com/openfaas/faas-cli/issues/443 and https://github.com/openfaas/faas-cli/issues/401
When OpenFaas is not deployed and the machine is not part of a swarm
```
$ /home/martindekov/go/src/github.com/openfaas/faas-cli/faas-cli deploy -f long-task.yml
Deploying: long-task.
Is FaaS deployed? Do you need to specify the --gateway flag?
Put …
```
> Add exit code 1 for functions that exit with status different than 200 or 202

- Gopkg.lock
- Gopkg.toml
- commands/deploy.go
- proxy/deploy.go
- proxy/deploy_test.go
- stack/schema.go
- vendor/github.com/openfaas/faas/gateway/requests/requests.go
- Add the ReadOnlyRootFilesystem option to the stack schema
- Pass the value of ReadOnlyRootFilesystem to the create function
request
- Update the vendor lock to bunp the faas version
- Update the vendor lock to include docker-credential-helper because it
was required to build correctly
Closes openfaas/faas#590
This will be parsed into the add function request and then to the
orchestration layer so that the function container is created with a
read-only filesystem at /)
I am posting this to get it in the pipeline and ready for testing, I will start testing it as soon as I have the companion pull requests in swarm and netes ready.
> Add ReadOnlyRootFilesystem to the schema

- builder/build.go
- builder/exec.go
- commands/build.go
- commands/deploy.go
- commands/push.go
With this commit the --tag is extended to include branch argument
which tags image not only with sha but branch-sha
Extend the --tag with branch feature which tags image with branch and sha.
Added checks to see the --tag argument if its branch it calls not only
GetGitSha, but also new function which checks the branch we are in.
If we are not in a repo it fails and if we are in a repo it gets the branch
and adds it to the image name name.
This references https://github.com/openfaas/faas-cli/issues/463.
Tested by building pushing and deploying image with my change.
Example pushed images are found in this docker hub repo:
https://hub.docker.com/r/martindekov/gofun/tags/
Adding ```image:<example name>:<example replacement of latest>``` …
> Extend --tag=branch which tags image with branch and sha

- commands/build.go
- commands/push.go
Invoking WaitGroup.Add() from a go routine can cause a race between it and
WaitGroup.Wait(). Add should always be invoked from the same context as Wait.
Fixes #469 
- Not tested yet.
> Fix a possible race between wg.Add and wg.Wait

- commands/generate.go
- schema/crd.go
This commit adds new subcommand `generate` faas-cli which can be used to
generate YAML file definition for Kubernetes CRD.
Output of this command can be piped to `kubectl` to apply to
Kubernetes cluster.
Usage: `faas-cli generate --api=openfaas.com/v1alpha2 --yaml fn-1.yml |
kubectl apply  -f -`
Fixes: #426
issue created by @alexellis  #426 
This has been tested on local kubernetes cluster with OpenFaaS operator. 
```sh
functions cat issue-bot.yml
provider:
name: faas
functions:
issue-bot:
lang: python3
handler: ./issue-bot
image: viveksyngh/issue-bot
environment_file:
- env.yml
➜  functions /Users/viveks/Repos/go-projects/src/github.com/openfaas/faas-cli/faas-cli generate --api=openfaas.com/v1alpha2 …
```
> Add `generate` command to create CRD YAML files

- commands/deploy.go
- commands/store_deploy.go
- schema/store_item.go
Add read only feature to `store deploy` command.
Currently, the `store deploy` command is not including `readOnlyRootFilesystem` from the store functions. The following change will implement this feature for the command, and will allow store
functions that are read-only to take affect.
Fixes: #490
Signed-off-by: James Smith <jamessmithsmusic@gmail.com>
References [[#490](https://github.com/openfaas/faas-cli/issues/490)].
Existing tests ran successfully.
Verified read-only root file system of store functions by the following steps :
- Set up Docker Swarm
- Pull a RO function (ex. `Figlet`)
- Validate RO RFS with the following commands
```
$ docker inspect <CONTAINER_ID> --format {{.HostConfig.ReadonlyRootfs}}
true
$ docker exec -it <CONTAINER_ID> sh
~ $ touch hello.txt
touch: hello.txt: …
```
> Implement read-only root file system for store

- commands/deploy.go
- commands/store_deploy.go
- schema/store_item.go
Adding support for annotations through annotation flag
to the faas-cli deploy and store-deploy.
The change adds support for annotations not only through yaml files but through the cli.
Extended faas-cli by adding `--annotations key=value` flag to the deploy and store deploy commands.
Closes #498 .
Created new function nfn.yml
```
$ cat nfn.yml
provider:
name: faas
functions:
nfn:
lang: go
handler: ./nfn
image: martindekov/nfn:latest
$ faas-cli deploy -f nfn.yml
...
$ curl -X GET http://127.0.0.1:8080/system/function/nfn
{"name":"nfn","image":"martindekov/nfn:latest","invocationCount":0,"replicas":1,"envProcess":"./handler","availableReplicas":0,"labels":{"com.openfaas.function":"nfn","com.openfaas.uid": …
```
> Add annotation flag support to the deploy and store-deploy

- commands/generate.go
- commands/generate_test.go
This commit add unit tests for `generate` verb of faas-cli.
Fixes: #492
#492 
```
provider:
name: faas
gateway: http://localhost:8080  # can be a remote server
functions:
hubstats:
lang: dockerfile
image: functions/hubstats:latest
skip_build: true
nodeinfo:
lang: dockerfile
image: functions/nodeinfo:latest
skip_build: true
echoit:
lang: dockerfile
image: functions/alpine:latest
fprocess: "cat"
skip_build: true
wordcount:
lang: dockerfile
image: functions/alpine:latest
fprocess: "wc"
skip_build: true
base64:
lang: dockerfile
image: functions/alpine:latest
fprocess: "base64"
skip_build: true
markdown:
lang: dockerfile
image: functions/markdown-render:latest
skip_build: true
```
```
/Users/viveks/Repos/go-projects/src/github.com/openfaas/faas-c …
```
> Add unit tests for generate command

- commands/up.go
Add `up` alias for `build` ➡︎ `push` ➡︎ `deploy`.
~~This reuses all the flags/logic from the respective commands which are chained together, it adds a single local flag `--push` which is used to include the push step.~~
~~Alternatives to setting `--push` would be to do so for non-`localhost`/`127.0.0.1` gateways perhaps. @alexellis wdyt?~~
This reuses all the flags/logic from the respective commands which are chained together, it adds a single local flag `--skip-push` which is used to exclude the push step.
Built and tested against a local gateway with both a local and docker hub image push/skip-push.
No unit tests added as it just reuses the underlying commands.
> Add `up` alias for build, push, deploy

- proxy/invoke.go
- proxy/invoke_test.go
This commit fixes issue with header parse for CLI which has `=` sign in
values. For instance `--header "X-Hub-Signature"="sha1=shashashaebaf43"`
This commit also adds unit tests for `parseHeaders` function.
Fixes: #509
issue raised by @alexellis  #509
> Fix issue with header parse with = in value

- commands/faas.go
- commands/new_function.go
- commands/new_function_test.go
This PR implements #481 
The fass-cli can now write the handler code to a directory that is different from the function name, by passing the `--handler` flag
My original motivation was being able to define the handler code as a python-importable module, in order to write some tests for it. But I realized that other people might have other requirements, and this is flexible enough to accommodate them.
I added a new test case to `commands/new_function_test.go`.
> Configurable handler directory

- builder/build.go
This change skips copy for `build` folder in copyDir
function to avoid the recursion while copying files.
Fixes: #478
Issue #478 
This has been tested on my local system.
```
kph-demo ls
handler.py       kph-demo.yml     requirements.txt
➜  kph-demo /Users/viveks/Repos/go-projects/src/github.com/openfaas/faas-cli/faas-cli build -f kph-demo.yml
2018/07/27 23:07:17 No templates found in current directory.
2018/07/27 23:07:17 Attempting to expand templates from https://github.com/openfaas/templates.git
2018/07/27 23:07:21 Fetched 13 template(s) : [csharp dockerfile go go-armhf java8 node node-arm64 node-armhf python python-armhf python3 python3-armhf ruby] from https://github.com/openfaas/templates.git
[0] > Building kph-demo.
Clearing …
```
> [WIP] Fixes issue with faas-cli build for same folder

- README.md
- commands/priority.go
- commands/template_pull.go
- commands/template_pull_test.go
- guide/TEMPLATE.md
Provides an override for template pull URL for env variable `OPENFAAS_TEMPLATES_URL`. 
The default template URL of `https://github.com/openfaas/templates.git` can be overriden in two places including an environmental variable
* 1st priority CLI input
* 2nd priority `OPENFAAS_TEMPLATES_URL` environmental variable
It takes a similar approach used for `OPENFAAS_URL`. 
Currently you can pass this as a parameter, but allowing an override would mean a user could customize this as a one-time thing in their bash profile.
[Issue-502](#502) 
The test is done based on the below criteria.  
criteria | CLI URL | ENV URL | Used URL
-----| ------ | ------- |------ 
None Provided | none | none | https://github.com/openfaas/templates.git. 
ENV Provided | none | https://github.com/s8sg/faaschain | …
> Override for template pull URL via ENV variable OPENFAAS_TEMPLATE_URL

- Gopkg.lock
- builder/build.go
* When we iterate through function handler, we need to name the
destination with the file/folder name we are currently inspecting
* Clean the file path before we give it to CopyFiles
Fixes #521
Tested manually for now
> Ensure that we name the copy dest correctly

- commands/up.go
This change adds `--skip-deploy` flag analogous to `--skip-push`
to the `faas-cli up` command. The requrement for this came from
user experience, as using `build` and `push` together without
`deploy` happens frequently
Signed-off-by: Ivana Yovcheva (VMware) <iyovcheva@vmware.com>
Raised by @alexellis on slack
`faas-cli-darwin up`
`faas-cli-darwin up  --skip-push`
`faas-cli-darwin up  --skip-push --skip-deploy`
`faas-cli-darwin up  --skip-deploy`
> Add `--skip-deploy` flag to `up` command

- commands/describe.go
- proxy/describe.go
- proxy/describe_test.go
- schema/describe.go
This commit adds a new verb `describe` to display information of an
OpenFaaS function.
Fixes: #446
(https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))
issue #446 
This has been tested on my local system. 
```
./faas-cli describe haveibeenpwned
Name:			haveibeenpwned
Status:			Not Ready
Replicas:		1
Available replicas:	0
Invocations:		0
Image:			functions/haveibeenpwned:0.1
Function process:
URL:			http://127.0.0.1:8080/function/haveibeenpwned
Async URL:		http://127.0.0.1:8080/async-function/haveibeenpwned
➜  faas-cli git:(describe_verb) ✗ ./faas-cli describe env
Name:			env
Status:			Ready
Replicas:		1
Available replicas:	1
Invocations:		0
Image:			functions/alpine:latest
Function process:	env
URL: …
```
> Add describe verb for a function

- Gopkg.lock
- README.md
- commands/invoke.go
- commands/invoke_test.go
- commands/list_test.go
- vendor/github.com/alexellis/hmac/README.md
- vendor/github.com/alexellis/hmac/pkg.go
Change adds the ability to sha1 sign invoke calls with a pre-shared key.
Signing requires  both the header value to store the hash (`--sign`) and the key (`--key`) used
to generate the hash so checking for both values is implemented.
Once the hash has been generated and the header value constructed the
header is appended to, and treated the same as, the existing set of headers.
Unit tests added to cover the new methods with the `generateSignedHeader()` tests
both generating and validating the generated values.
* Unit tests added an passing
* Build succeeds
* Post build testing:
➖Flags but no values:
```
$ echo OpenFaaS | ./faas-cli-darwin invoke figlet --sign  --key
Signing requires both --sign <header-value> and --key <key-value>
```
➖Flags with empty --key arg:
```
$ echo OpenFaaS | …
```
> Add message signatures to invoke command

- commands/describe.go
- proxy/describe.go
- proxy/describe_test.go
This commit align `faas-cli describe` output text to the left.
Fixes: #531
(https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))
Fixes #531 
```
./faas-cli describe figleta  -g http://142.93.39.213:8080/
No such function: figleta
./faas-cli describe figlet  -g http://142.93.39.213:8080/
Name:                figlet
Replicas:            1
Available replicas:  1
Invocations:         4
Image:               functions/figlet:0.1
Function process:
URL:                 http://142.93.39.213:8080/function/figlet
Async URL:           http://142.93.39.213:8080/async-function/figlet
```
> Update describe verb to align text left

- README.md
Those instructions are outdated and are confusing users and
causing errors. Pointing to the latest exe file instead
Signed-off-by: Ivana Yovcheva (VMware) <iyovcheva@vmware.com>
Raised on slack
N/A
> Remove instructions for scoop

- commands/new_function.go
This change alters the mode of operation so that the `new` command only concerns itself with the function that the user is trying to create.  The deduplication to avoid multiple functions with the same name remains in place and the generated yaml is either written to a new file or appended to the existing file depending upon whether the user supplied `--append`. 
Restores the yaml file append functionality that 973a75291e84901ca73837822337749da875876c introduced and e509cc7476a0c5f2c2e5d9e74b724e2e3ea833dd built upon that was inadvertently removed in 2186a07ebb639d099b10f06e1910d35980a15c4b through the introduction of parsing of the services struct via a golang template.
The template would rewrite the entire file based on the content of the services struct which would cause attributes …
> Restore file append functionality to `faas-cli new`

- builder/build.go
- Skip both `build` and `template` from the stack root directory because these are temporary folders that should not be considered part of the
handler code
I would like to improve the tests here, but I need to think about the best way to implement them.
Fixes #478  
Manual testing with a go template, a Dockerfile function, a python template, and @kenfdev custom go-http template
- [ X I have signed-off my commits with `git commit -s`
> Skip template folder during the build

- README.md
- commands/priority.go
- commands/priority_test.go
- commands/template.go
- commands/template_pull.go
- commands/template_pull_test.go
- commands/template_store.go
- commands/template_store_list.go
- commands/template_store_pull.go
- guide/TEMPLATE.md
Moving template command as own command which has store and
pull commands as subcommands. Also adding store list and
store pull commands to list and pull from store
Also opened Issue in store which slaps the keys: [43](https://github.com/openfaas/store/pull/44)
This PR separates `template pull` command into separate commands and adding additional `template store list` and `template store pull` for interactions with the official templates store.
The commands are structured the following way:
* `template`
* `pull`
* `store`
* `list`
* `pull`
And are used as before, there are the ways you can use every command now:
`faas-cli template pull <URL OF REPOSITORY>`' <- (default)
`faas-cli template pull <URL OF REPOSITORY> --overwrite` …
> Add template store command

- README.md
- commands/template_store_describe.go
- guide/TEMPLATE.md
Adding template store describe command to output
the whole json template object aka. describing the
template
Adding `template store describe` to output the fields in the `.json` template object
Adds a way to describe a single template by outputting every field from the json struct the following way:
```
> ./faas-cli template store describe go
Name:              go
Platform:          x86_64
Language:          Go
Source:            openfaas
Description:       Official Golang template
Repository:        https://github.com/openfaas/templates
Official Template: true
```
The store location URL is copied from list so it is `argument` > `env_var` > `default`
Closes #563 
Manual:
```
> ./faas-cli template store describe
Need to specify one …
```
> Add template store describe

- commands/template_store_list.go
- commands/template_store_list_test.go
Adding platform flag to template store to filter
the templates by platform
Adding `--platform` flag to filter by platform
Adding `--platform`/`-p` flag to filter templates by existing platforms from `PLATFORM` field 
Closes #570 
Manually:
Normal invocation of command:
```
> ./faas-cli template store list
NAME                    SOURCE             DESCRIPTION
csharp                  openfaas           Official C# template
dockerfile              openfaas           Official Dockerfile template
go-armhf                openfaas           Official Golang armhf template
go                      openfaas           Official Golang template
java8                   openfaas           Official Java 8 template
node-arm64              openfaas …
```
> Add platform flag to template store

- README.md
- commands/build.go
- commands/fetch_templates.go
- commands/fetch_templates_test.go
- commands/template_pull.go
- commands/template_pull_test.go
- guide/TEMPLATE.md
- versioncontrol/git.go
- versioncontrol/parse.go
- versioncontrol/parse_test.go
Update `template pull` command to parse a git reference name from the
trailing hash/url fragment in the git url. This allows the user to pin the template to a specific revision or tag or even update from a specific branch.
- Add parsing utilities to check for a pinning value in the git url
- Updates git clone command to specify the branch flag
- Adds git command to validate the reference name
- Updates and adds unit tests for the new parsing
Resolves #573 
I have manually tested it locally with a private template repository.   I have used `faas-cli template pull` with my private repository, with a tag and without a tag, as well as empty with the default OF template repo.
Additionally, unit tests have been added to validate the url parsing.
Because the pin separator is `#`, this was …
> Implement pinned template repo clone

- commands/secret.go
- commands/secret_list.go
- proxy/secret.go
- schema/secret.go
This commit adds `faas-cli secret list` command to the faas-cli which
will be used to get secret list from the cluster.
#577 
Tested on local Docker for Mac with faas-swarm.
```
./faas-cli secret ls -g http://127.0.0.1:8081
NAME
test
```
> Add secret list command to faas-cli

- commands/secret_list.go
- commands/secret_remove.go
- commands/secret_remove_test.go
- proxy/secret.go
Add faas secret remove command
- adds secret remove command
Contributes to #577 
- adds unit tests to validate arguments list
Tested with faas-netes as back-end and latest YAML files in ./yaml/
> Add faas secret remove command

- commands/secret_create.go
- proxy/secret.go
- schema/secret.go
This commit adds command to create new secrets from the CLI
#577 
Tested on my local for docker for mac and Kubernetes
```
./faas-cli secret create test-secret --value=test
Creating secret: test-secret
server returned unexpected status code: 500 - secrets "test-secret" already exists
./faas-cli secret create test-secret --from-file ~/Downloads/openfaas-cloud.2018-04-11.private-key.pem
Creating secret: test-secret
server returned unexpected status code: 500 - secrets "test-secret" already exists
./faas-cli …
```
> Add create command for secrets

- commands/deploy.go
- commands/secret_create.go
- commands/secret_list.go
- commands/secret_remove.go
- commands/secret_update.go
- this flag was added by the original author, but was not present
in the help messages.
I saw this was lacking in the code.
Via `go build` and running `faas-cli secret COMMAND --help`
> Adds tls-no-verify to secrets commands help

- commands/login.go
The documentation uses admin as a default, so we can save users
on some typing and complexity by defaulting this CLI parameter.
It can still be overriden if needed.
n/a
CI
> Default login to username of admin

- commands/deploy.go
Signed-off-by: Rishabh Gupta<r.g.gupta@outlook.com>
The error message at deploy time said "faas template pull" instead of "faas-cli template pull"
Not needed
> Fixed error message

- README.md
- commands/generate_test.go
- commands/new_function.go
- commands/new_function_test.go
- sample/github_hmac/Dockerfile
- sample/hmac.yml
- sample/imagemagick/Dockerfile
- stack.yml
- stack/stack_test.go
Rename provider YAML faas to openfaas
The provider name value of faas is archaic and should be changed
to openfaas. The CLI code already supports this but the generated
values use the text faas still.
* 1) Running this in the faas-cli folder:
```
faas-cli up
```
* 2) Running `./make_dist.sh`
* 3) Generating and running `up` on a new function with the updated binary:
Example:
```
provider:
name: openfaas
functions:
name:
lang: go
handler: ./name
image: name:latest
```
> Rename provider YAML name from faas to openfaas

- commands/secret_create.go
- commands/secret_create_test.go
This commit add validation (subdomain in RFC-1123) for secret name while
creating the secret name.
Fixes #590
#590 
```
./faas-cli secret create my-secret --from-literal=value
Creating secret: my-secret
Created: 201 Created
➜  faas-cli git:(add_secrent_name_validation) ./faas-cli secret create my_secret --from-literal=value
ERROR: invalid secret name: my_secret, secret name must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (regex used for validation is ^[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$)
```
> Add validation for secret name

- builder/build.go
- builder/build_test.go
- removes custom logic for working with Dockerfile language to
be in-line with the the new Dockerfile template
https://github.com/openfaas/openfaas-cloud/issues/421
- tested with faas-cli build [--shrinkwrap] with Dockerfile
language template and with node template to check for regression
- added unit test for new method
> Allow shrinkwrap of Dockerfile template

- builder/build.go
- builder/build_test.go
- commands/build.go
This changes add --build-label flag to function build command which can
be used to add additional metadata information for function images using
docker labels.
Fixes #567
#567
Tested on my local on Docker for mac. 
1. Create a new function using 
`faas-cli new label-func --lang=python --prefix=viveksyngh`
2. Build the function and pass build label values 
`./faas-cli build --build-label org.label-schema.vcs-url="https://github.com/nginx/nginx"  --build-label org.label-schema.description="Test function with docker labels"`
3. Then inspect the docker image with below command
`docker inspect viveksyngh/label-func` 
```json
...
"Labels": {
"org.label-schema.description": "Test function with docker labels",
"org.label-schema.vcs-url": …
```
> Add build-label flag for build command

- README.md
- commands/new_function.go
- commands/new_function_test.go
Allow --prefix flag for new command
As requested in #550 - this allows a prefix to be supplied
when generating new functions.
Tested on MacOS with a local build and with 3 additional
unit tests.
> Allow --prefix flag for new command

- Gopkg.lock
- Gopkg.toml
- commands/generate.go
- commands/generate_test.go
- commands/store.go
- commands/store_deploy.go
- commands/store_inspect.go
- commands/store_list.go
- proxy/function_store.go
- vendor/github.com/pkg/errors/.gitignore
- vendor/github.com/pkg/errors/.travis.yml
- vendor/github.com/pkg/errors/LICENSE
- vendor/github.com/pkg/errors/README.md
- vendor/github.com/pkg/errors/appveyor.yml
- vendor/github.com/pkg/errors/errors.go
- vendor/github.com/pkg/errors/stack.go
Generate CRD from store images
This feature adds the support for deploying to the operator using
a CRD from the Function Store. A new flag --from-store can be
passed that allows for matching upon the name. It means we can now
easily deploy figlet and similar functions to the operator through
CRDs.
Tested with new unit tests and manual testing to generate a CRD
positive / negative testing using the strings figlet / filgets.
> Generate CRD from store images

- Gopkg.lock
- Gopkg.toml
- commands/generate.go
- commands/generate_test.go
- commands/store.go
- commands/store_deploy.go
- commands/store_inspect.go
- commands/store_list.go
- proxy/function_store.go
- schema/knative/v1alpha1/serving.go
- vendor/github.com/pkg/errors/.gitignore
- vendor/github.com/pkg/errors/.travis.yml
- vendor/github.com/pkg/errors/LICENSE
- vendor/github.com/pkg/errors/README.md
- vendor/github.com/pkg/errors/appveyor.yml
- vendor/github.com/pkg/errors/errors.go
- vendor/github.com/pkg/errors/stack.go
Add knative serving v1alpha1 to generate CRD command
This commit adds the ability to generate a knative serving
definition from the Function Store or a stack.yaml file with
a basic definition including: namespace, name, env-vars and
image.
Allows OpenFaaS images and the function store to be deployed to Knative
Tested with Istio on Packet.net using figlet.
> Add knative serving v1alpha1 to generate CRD command

- commands/deploy.go
- commands/describe.go
- commands/remove.go
- commands/secret_create.go
- commands/secret_list.go
- commands/secret_remove.go
- commands/secret_update.go
- commands/store_deploy.go
- commands/version.go
- proxy/auth.go
- proxy/delete.go
- proxy/deploy.go
- proxy/deploy_test.go
- proxy/describe.go
- proxy/secret.go
- proxy/version.go
I tested all the commands changes on my cluster.
```
Test
/faas-cli-darwin deploy  -g "http://gw.viveksyngh.me:31112" --token "$TOKEN"
Deploying: stronghash.
URL: http://gw.viveksyngh.me:31112/function/stronghash
Deploying: nodejs-echo.
URL: http://gw.viveksyngh.me:31112/function/nodejs-echo
Deploying: shrink-image.
URL: http://gw.viveksyngh.me:31112/function/shrink-image …
```
> Add token to commands

- commands/auth.go
- commands/deploy.go
- commands/describe.go
- commands/list.go
- commands/remove.go
- commands/secret_create.go
- commands/secret_list.go
- commands/secret_remove.go
- commands/secret_update.go
- commands/store_deploy.go
- commands/version.go
- proxy/auth.go
- proxy/delete.go
- proxy/deploy.go
- proxy/deploy_test.go
- proxy/describe.go
- proxy/list.go
- proxy/secret.go
- proxy/version.go
Opens browser for user to authenticate using the implicit grant
flow. https://oauth.net/2/grant-types/implicit/
A temporary HTTP server is started to receive the token, which
is only available via JavaScript in a URL fragment. The embedded
JavaScript is used to send the token to the server to be
returned to the user.
The patch includes a temporary update to the list command so
that a --token argument can be passed in instead of basic-auth.
Part of #647 
Tested e2e with my oidc-plugin and Auth0.
Special thanks to @LucasRoesler for his input.
Begin the auth workflow:
```
./faas-cli auth -g http://my-gateway-online:8080 \
--client-id=myid  \
--auth-url=https://tenant-goes-here.eu.auth0.com/authorize  \
--audience …
```
> [WIP] Auth command for OAuth2 / OIDC

- README.md
- commands/auth.go
- commands/auth_test.go
When passing no parameters or empty values the current version
was attempting to initiate an OAuth2 flow, when it would have
been invalid.
This patch fixes that and has been tested end-to-end so show the error presents.
```
alext:faas-cli alex$ ./faas-cli auth
--auth-url is required and must be a valid OIDC /authorize URL
alext:faas-cli alex$ ./faas-cli auth --auth-url x
--auth-url is an invalid URL: x
alext:faas-cli alex$ ./faas-cli auth --auth-url http://x/authorize
--client-id is required
alext:faas-cli alex$ ./faas-cli auth --auth-url http://x/authorize --client-id=123
Starting local token server on port 31111
Launching browser: http://x/authorize?audience=&client_id=123&nonce=1561621756972359000&redirect_uri=http%3A%2F%2F127.0.0.1%3A311 …
```
> Add empty flag validation to auth command

- README.md
- commands/auth.go
- commands/auth_test.go
Adds client_credentials to auth command for machine-to-machine auth
such as CI/CD.
Feature for: #647
This patch adds the client_credentials flow so that it can be
used in CI/CD processes for deploying to the OpenFaaS gateway
without using an interactive flow.    
Tested e2e with Auth0 and a Machine2Machine App type.
Tested that there is no regression in UI / gateway code flow, or
the implicit flow.
> Add client_credentials to auth command for machine-to-machine auth

- commands/template_store_list.go
Move the call to `filterTemplate()` into the `formatTemplatesOutput()` function and then test for a non-zero slice length before proceeding.  As the templates slice is filtered higher up this removes the need to call in to `filterTemplate()` within the two output functions, which consequently also removes the need to pass platform into them.
An issue existed whereby `arm64` templates would not display in the `template list` command.
The cause was located within the `formatTemplatesOutput()` function which was seemingly doing some pre-filtering to ascertain whether the output should return empty if no templates matching the supplied pattern were found.  Within this function a comparison was being performed of the template.Platform …
> Fix `template store list` command

- commands/logs.go
- proxy/list.go
- proxy/logs.go
- proxy/logs_test.go
- Add the token flag to the logs command, this allows users to oauth as
well as basic auth.
- additionally add some basic test for the GetLogs method and use the
SetToken helper in the List command
Resolves #656 
A new unit test in the proxy package verifies the behavior
> Add token auth support to the logs cmd

- proxy/secret.go
- proxy/secret_test.go
This PR adds support for handling `409 CONFLICT` status codes returned by the OpenFaaS gateway when trying to create a secret that already exists. It is a companion PR to https://github.com/openfaas/faas-netes/pull/468.
I believe https://github.com/openfaas/faas-netes/pull/468 contains all the required details.
I've tested it by extending the existing unit tests.
> Handle '409 CONFLICT' during secret creation.'

- commands/logs.go
- Remove trailing newlines from log messages to avoid double spacing the
log stream when it is printed to stdout.  The current implementation
results in empty lines between each log line, this looks odd for users.
This commit ensures there is not an empty line between log lines.
Resolves #659
Manually tested using the faas-netes local development cluster
1. in faas-cli, run `make local-install`
2. in faas-netes, run `make start-kind`
3. deploy figlet
```
$ export OFG=http://127.0.0.1:31112
$ faas-cli store deploy figlet -g=$OFG
Post http://127.0.0.1:31112/function/figlet: EOF
$ echo "tester" | faas-cli invoke echo -g=$OFG
_            _
| |_ ___  ___| |_ ___ _ __
| __/ _ \/ __| __/ _ \ '__|
| ||  __/\__ \ ||  __/ |
\__\___||___/\__\___|_|
```
4. check the logs with `kubectl` and …
> Trim newlines from log messages

- Gopkg.lock
- Gopkg.toml
- commands/list_test.go
- proxy/deploy.go
- proxy/describe.go
- proxy/describe_test.go
- proxy/list.go
- proxy/list_test.go
- vendor/github.com/openfaas/faas-provider/types/config.go
- vendor/github.com/openfaas/faas-provider/types/model.go
- vendor/github.com/openfaas/faas-provider/types/requests.go
- vendor/github.com/openfaas/faas/LICENSE
- vendor/github.com/openfaas/faas/gateway/requests/requests.go
Move to use faas-provider vs gateway for function structs
This patch moves the CLI away from using the gateway function
structs from the requests package and over to the faas-provider.
Tested with e2e testing and build_redist.sh
Refactoring.
> Move to use faas-provider vs gateway for function structs

- commands/logs.go
- commands/logs_format.go
- commands/logs_format_test.go
- flags/log_format.go
- flags/log_format_test.go
- flags/time_format.go
- flags/time_format_test.go
- Add new flags to toggle the name, instance, and timestamp fields.
Additionally, the new `time-format` also allows controlling the actual
timestamp format.
- Also provide the log format flag to allow printing the output as JSON,
key-values, or the plain format.  This should make it easy to integrate
with other tools, like JQ etc.
Resolves #671 
Additional unit tests are provided for the formatters. Additionally, this has been tested in the faas-netes test environment
```sh
$ make start-kind
$ make local-install
$ echo "test" | faas-cli --gateway=http://localhost:31112 invoke echo
test
$ echo "test" | faas-cli --gateway=http://localhost:31112 invoke echo
test
$ echo "test" | faas-cli --gateway=http://localhost:31112 invoke echo
test
$ faas-cli --gateway=http://localhost:31112 logs echo …
```
> Add flags to control the log output format

- commands/build.go
- commands/build_test.go
- commands/new_function.go
- commands/new_function_test.go
Adds priority checking for the environment variable override for the remote url to pull templates from.  This was already being respected in `template pull` but was being ignored when opportunistically pulling templates during `build` and `new`.
Addresses issue #685 which properly points out that these commands were ignoring the environment variable.
Starting with an empty directory:
```bash
$ ./faas-cli new --lang=go test-fn
2019/09/05 11:54:48 No templates found in current directory.
2019/09/05 11:54:48 Attempting to expand templates from https://github.com/openfaas/templates.git
2019/09/05 11:54:48 Fetched 17 template(s) : [csharp csharp-armhf dockerfile dockerfile-armhf go go-armhf java12 java8 node node-arm64 node-armhf php7 python python-armhf python3 python3-armhf ruby] from …
```
> Respect env var for template url for `new` and `build`

- commands/completion.go
- commands/completion_test.go
This PR adds a new command called `completion` which generates auto complete shell configuration for Bash and ZSH. Heavily inspired by [kubectl](https://github.com/kubernetes/kubectl/blob/master/pkg/cmd/completion/completion.go).
Added code testing in `commands/completion_test.go`.
The installation and testing of the auto completion is heavily inspired by the [kubectl docs](https://kubernetes.io/docs/tasks/tools/install-kubectl/#enabling-shell-autocompletion). 
The PR has a 99% copy and paste piece of code from [kubectl](https://github.com/kubernetes/kubectl/blob/master/pkg/cmd/completion/completion.go#L145). Basically, `cobra`'s `GenZshCompletion` function is broken and what the copied code does is convert the `GenBashCompletion` to work with ZSH. **I don't understand all of that code**, …
> Add new completion command supporting bash and zsh

- commands/bash_completion.go
- commands/completion.go
This PR add the final touches in the `completion` command.
- `./faas-cli bashcompletion` should emit deprecated message
- `./faas-cli completion --help` should display docs link
> Final touches completion command

- Gopkg.lock
- Gopkg.toml
- commands/deploy.go
- commands/describe.go
- commands/list.go
- commands/remove.go
- commands/store_deploy.go
- proxy/delete.go
- proxy/delete_test.go
- proxy/deploy.go
- proxy/deploy_test.go
- proxy/describe.go
- proxy/describe_test.go
- proxy/list.go
- proxy/list_test.go
- proxy/utils.go
- proxy/utils_test.go
- stack/schema.go
- vendor/github.com/openfaas/faas-provider/logs/handler.go
- vendor/github.com/openfaas/faas-provider/types/config.go
- vendor/github.com/openfaas/faas-provider/types/model.go
Adding support for namespaces on the following commands:
- delete
- deploy
- describe
- list
- store deploy
- remove
Adding support for the namespaces feature for the cli https://github.com/openfaas/faas-netes/issues/511 
Closes #693 
Manually and unit tests on Kubernetes.
The commands let you deploy functions in namespaces with the `-n` flag. In order to make that work, deploy the latest `faas-netes` and create namespace with `openfaas=1` annotation.
To deploy function from file, you just have to add `namespace: <your_namespace>` below the function, aligned with `image: ..` `annotations: ...`
> Add support for namespaces

- CONTRIBUTING.md
Signed-off-by: Jonatas Baldin <jonatas.baldin@gmail.com>
Remove deprecated `Bash Auto-Completion` section from CONTRIBUTING. I also didn't add about the new `completion` command because it's already documented in the docs.
> Remove deprecated auto completion section from CONTRIBUTING

- Gopkg.lock
- Gopkg.toml
- commands/secret_create.go
- commands/secret_list.go
- commands/secret_remove.go
- commands/secret_update.go
- proxy/secret.go
- proxy/secret_test.go
- schema/secret.go
- vendor/github.com/openfaas/faas-provider/types/model.go
This commit updates the secret commands to use `Secret` struct from the
faas-provider rather than using it's own struct.
I would like to do this change as a pre-work for this issue #701 
I have tested this on my local with swarm and kubernetes.
swarm
```
./faas-cli-darwin secret ls
No secrets found.
➜  faas-cli git:(secret-update) ✗ ./faas-cli-darwin secret create test-swarm-secret --from-literal=test-swarm-value
Creating secret: test-swarm-secret
Created: 201 Created
➜  faas-cli git:(secret-update) ✗ …
```
> Use Secret struct from faas-provider

- commands/secret_create.go
- commands/secret_list.go
- commands/secret_remove.go
- commands/secret_update.go
- proxy/secret.go
- proxy/secret_test.go
This commit add `--namespace` flags to the secret subcommand in order to
support multiple namesapces feature.
Fixes: #701 
This has been tested on local kubernetes cluster. 
```
faas-cli git:(add-namespace-to-secret) ✗ ./faas-cli-darwin secret ls
http://127.0.0.1:31112/system/secrets
No secrets found.
➜  faas-cli git:(add-namespace-to-secret) ✗ ./faas-cli-darwin secret ls -n fn
http://127.0.0.1:31112/system/secrets?namespace=fn
No secrets found.
➜  faas-cli git:(add-namespace-to-secret) ✗ clear
➜  faas-cli …
```
> Add namespace flag to secrets commands

- commands/list.go
This commit fixes the issue with `cloud seal` command `--namespace`
flag. Since default value for `--namespace` flag for cloud is different
than other commands `--namespace` flag. It was getting overriden by
`--namespace` flag value from list command. This commit changes the
variable used for `--namespace` flag in `list` command.
Fixes: #709 
I have tested this in my local.
```
./faas-cli cloud seal --name alexellis-github --literal hmac-secret=c4488af0c158e8c
Sealing secret: alexellis-github in namespace: openfaas-fn
Unable to load public certificate pub-cert.pem
➜  faas-cli git:(issue-708) ./faas-cli cloud seal --name alexellis-github --literal hmac-secret=c4488af0c158e8c --namespace=fn
Sealing secret: alexellis-github in namespace: fn …
```
> Fix issue with cloud seal command

- commands/auth.go
- commands/login.go
- config/config_file.go
- config/config_file_test.go
- proxy/auth.go
- proxy/auth_test.go
- proxy/list.go
This commit saves oauth2 tokens to the openfaas config file with a
different auth type. The different auth type helps to determine whether
it is basic auth token or oauth2 token. It also refactors existing
config file function to cater the needs of auth command.
Fixes: #663
In this PR I have implemented the saving oauth2 tokens to the config file as per discussed architecture and also added the support to the `faas-cli list` command. It this approach looks, I can go ahead and implement the same in other commands.
#663 
I have tested it on my local with a gateway which has oauth2 enabled.
```
./faas-cli auth --auth-url https://dev-cqxdj5cl.auth0.com/authorize --audience https://dev-cqxdj5cl.auth0.com/api/v2/ --client-id …
```
> Save oauth tokens to the openfaas config file

- commands/fetch_templates.go
- commands/template_pull.go
- commands/template_pull_stack.go
- commands/template_pull_stack_test.go
- commands/template_pull_test.go
- stack/schema.go
Adding template pull stack command which will pull template
from configuration field in the function yaml or from separate
yaml file with that same field
Adding `template pull stack` command to the cli to pull templates configured in yaml file in field looking the following way:
```
configuration:
templates:
- name: perl-alpine
- name: rusta
source: https://github.com/openfaas-incubator/openfaas-rust-template
```
The output is in the following format when `--repo` flag is not present:
```
Pulling template: perl-alpine from configuration file: stack.yml
Fetch templates from repository: https://github.com/tmiklas/openfaas-perl-templates at master
2019/10/21 23:21:36 Attempting to expand templates from …
```
> Add template pull stack

- README.md
- npm/.npmrc
- npm/README.md
- npm/cli.js
- npm/install.js
- npm/package.json
Signed-off-by: Brian Woodward <brian.woodward@gmail.com>
This PR introduces an `npm` package that, when installed, will run a `postinstall` script to download and install the latest version of the `faas-cli`.
Related to issue #645 
Still a work in progress and only tested on Mac OSX (darwin).
> NPM package for installing faas-cli

- proxy/auth.go
- proxy/auth_test.go
- proxy/list.go
Add oauth2 token support to all system commands which requires
authentication. This commit also removes AddAuth method and adds the
same logic to SetAuth method. I have tested this on my local local
kubernetes cluster with Oauth2 enabled using auth0.com.
Fixes: #715 
```
./faas-cli-darwin auth --auth-url https://dev-cqxdj5cl.auth0.com/authorize --audience https://dev-cqxdj5cl.auth0.com/api/v2/ --client-id "4cCLcJDzkvQ2aQ11aHt7iLpbVfuPDOEk" -g http://gw.viveksyngh.me
Launching browser: https://dev-cqxdj5cl.auth0.com/authorize?audience=https%3A%2F%2Fdev-cqxdj5cl.auth0.com%2Fapi%2Fv2%2F&client_id=4cCLcJDzkvQ2aQ11aHt7iLpbVfuPDOEk&nonce=1572763064187499000&redirect_uri=http%3A%2F%2F127.0.0.1%3A31111%2Foauth%2Fcallback&response_type=token&scope=&s …
```
> Add oauth2 token support to all commands

- proxy/deploy.go
- proxy/deploy_test.go
When deploying a function the namespace will be displayed as it should in the gateway endpoint. The change is done by @rgee0 as per his commit. I tested and opened the PR from his name.
Closes #717 
Built the cli and deployed nodeinfo
```
mdekov@mdekov-Lenovo-Y520-15IKBN:~/go/src/github.com/martindekov/newFunction$ ../../openfaas/faas-cli/faas-cli store deploy nodeinfo  -g http://192.168.99.100:31112
URL: http://192.168.99.100:31112/function/nodeinfo
mdekov@mdekov-Lenovo-Y520-15IKBN:~/go/src/github.com/martindekov/newFunction$ ../../openfaas/faas-cli/faas-cli store deploy nodeinfo  -g …
```
> Add namespace to outputted deployed URL

- commands/template_pull.go
This commit re-introduces the line which determines what value should be used for the repository before the code heads off into pullTemplate()
Rework in #668 removed the call to getTemplateURL() which set `repository` to a value based on a precedence order.  This meant that an argument needed to be passed to `faas template pull` in order for it to complete without error, which had implications for pulling of the standard templates using the bare command.
Built from master:
```
$ ./faas-cli-darwin version
|_|
CLI: …
```
> Restore getTemplateURL() in template pull

- README.md
In the ofc-bootstrap repo we have scripts thats overrides the default controller name to ofc-sealedsecrets-sealed-secrets
> Updated outdated kubeseal arguments

- README.md
- commands/cloud.go
- commands/version.go
- commands/version_test.go
Download kubeseal via faas-cli cloud seal command 
Closes: #722 and closes: #724 by @utsavanand2 💪 🙏 
This is the combination of the approach taken by @utsavanand2 and
the guidance offered by @rgee0 and @LucasRoesler combined into
a single PR. It also uses the GitHub HTTP website instead of the
GitHub API - the GitHub API has a rate-limit of 50 requests per
hour and is likely to get exhausted quickly, so this approach
removes the issue in #724.
Given that there is only one executable needed at this stage, the
download command idea was removed in favour of a simple flag. The
flag will be updated in the README.md and documentation after
the merge and release.
Tested with --download and --download-version with an override
on MacOS.
> Download kubeseal via faas-cli cloud seal command 

- stack.yml
- stack/stack.go
- stack/stack_test.go
Depreciate generic "faas" provider for "openfaas"
The openfaas provider was introduced as a default over 8 months
ago, so anyone still using the generic and legacy term "faas"
should update their stack.yml file. Simply replacing "faas" with
"openfaas" is sufficient, all files created over the past
8 months+ should already have this text.
This is the final step of the depreciation of the legacy
provider "faas" and has no bearing on functionality.
With the stack.yml file and through the unit tests.
> Depreciate generic "faas" provider for "openfaas"

- commands/build.go
- commands/template_pull_stack.go
- commands/template_pull_stack_test.go
- stack/schema.go
Adding functionality which will pull templates defined in the
function YAML file. Additionaly added overwrite flag to the
build command in order to enable the command to overwrite
templates. Also removed the filtering funcitonality from template
pull stack command and renamed the method which will be used to
pull the configuration
Configuration in stack.yml file was used only by `template pull stack` command. Now the configuration is additionally red in the building phase of the function.
Adding `--overwrite` flag to the `faas-cli build` command as it reads and pull templates
defined in the function YAML file. Removing the filtering logic of the `template pull stack`
along with its testing as requested and renaming the method responsible for …
> Add stack file template configuration to build

- commands/namespaces.go
- proxy/namespaces.go
- proxy/utils.go
Adding namespaces command with which you can
list the namespaces available to the openfaas
instance to deploy functions to
Adding `namespaces` command which will list all the namespaces like so:
```
$ ./faas-cli namespaces --gateway=http://192.168.99.103:31112
Namespaces:
- openfaas-fn
```
Closes #728 
```
$ ./faas-cli namespaces --gateway=http://192.168.99.103:31112
Namespaces:
- openfaas-fn
```
> Add namespaces command

- commands/invoke.go
- proxy/invoke.go
- proxy/invoke_test.go
This appears to be a miss in the PR that added namespace support.
Add --namespace to invoke command
Missing from #693 
```sh
go build && uname|./faas-cli invoke --namespace=dev stronghash -g 192.168.0.26:31112
go build && uname|./faas-cli list -g 192.168.0.26:31112 -n dev
Function                        Invocations     Replicas
stronghash                      0               1    
```
> Add --namespace to invoke command

- commands/describe.go
- commands/describe_test.go
Name spaces have been appended to both the url and async url in the command package function getFunctionURLs.
Fixes #739 
I have created a table test that ensures the expected URLs are generated for DNSs with and without ports, as well as for functions with and without namespaces.
I also built the faas-cli app on my MacOS using MiniKube and OpenFaaS installed with k3sup. I then enabled namespaces, a new feature as of this comment. I followed the instructions in the following pages to set up my system:
* https://docs.openfaas.com/deployment/kubernetes
* https://docs.openfaas.com/reference/namespaces/
I ran the describe command with `./faas-client describe <function> -n <namespace>` and `./faas-client describe <function>` and saw the expected URLs. See screenshot:
> Describe function command should include namespace in urls

- commands/cloud.go
Based on suggestion in  #749 to return error on non-200 status code rather than download the 404 HTML page.
We now show the user we got a non 200 status code, and return.
Signed-off-by: Alistair Hey <alistair@heyal.co.uk>
```
GOARCH=arm GOARM=6 go build
#On ARM 
pi@raspberrypi:~ $ ./faas-cli cloud seal --download
Starting download of kubeseal v0.9.6, this could take a few moments.
Could not find release, http status code was 404, release may not exist for this archetecture
heyal@heyal-xps:~/go/src/github.com/openfaas/faas-cli$ ./faas-cli cloud seal --download
Starting download of kubeseal v0.9.6, this could take a few moments.
Download completed, please run:
chmod +x /tmp/kubeseal
/tmp/kubeseal --version
sudo install /tmp/kubeseal /usr/local/bin/
```
> Return an error if kubeseal release is not found

- builder/build.go
- builder/copy.go
- commands/build.go
- commands/faas.go
- commands/new_function.go
- commands/version.go
- guide/TEMPLATE.md
- stack/schema.go
Add ability to specify handler folder for a template as defined in 
issue #754
Fixes: #754
* The destination folder for the user's function / handler was
hard-coded to ./function/ or ./ for the Dockerfile template, this
patch allows users to override the value in template.yml
* Set handler_folder to a custom value such as "src"
* Updated new command for new handler path - the new command
needs to decide whether to find its templated handler code in the 
function folder or a custom folder.
Tested by updating the node template to use a handler_folder of
src, the build failed, then the Dockerfile was updated to match
the src folder instead of function, this resolved the error
and once deployed, it worked as expected.
Tested …
> Add ability to specify handler folder for templates

- builder/build.go
- builder/build_test.go
- commands/build.go
- stack/schema.go
- Extend the yaml schema specification to add `copy_extra_paths` to the stack `configuration` section
- Extend the behavior of `createBuildTemplate` to accept a slice of additional paths that should be copied into the build context
- Add a new flag `copy-extra` per the design request in  https://github.com/openfaas/faas-cli/issues/322#issuecomment-543127450 that allows the user to supply additional build folders to add to the `copy_extra_paths`
- Includes a new unit test to ensure that the extra paths copy can not copy folders from outside the current project. This is the same behavior and nearly the same implementation as is found in the `docker build`
Resolves #322 
The attached [faas-cli-test-binaries.zip](https://github.com/openfaas/faas-cli/files/3998791/faas-cli-test-binaries.zip) …
> [Feature] Copy common files into each function's handler folder

- .travis.yml
- Always push image with latest tag to docker hub
- Always push image with latest tag to quay.io
Tag and push the image for docker hub and quay.io in travis
#772 
I don't know how to test it. Please show me how.
> Fixes #772: Push latest image to Docker Hub

- commands/auth.go
- commands/auth_test.go
Allows an id_token to be used and the id_token flow instead
of the access_token which may have been incorrect.
Fixes an issue reported when used with Azure which was not
reproducible with Auth0/GitLab.
> Use an id_token for implicit flow

- proxy/client.go
- proxy/client_test.go
- Refactor the proxy request construction so that it preserves the
gateway base path.  The update to use the proxy client everywhere
in openfaas/faas-cli#753 changed the gateway address behavior.
Specifically the usage ResolveReference strips the base path from
the Gateway address when the path starts with a `/`, breaking
the previous behavior that respected the base path.
Resolves #787
I have updated the existing unit test that verifies this exact behavior. 
I have also tested this manually with our existing openfaas installation that was not accessible previously with the latest release (0.12.2)
> Support base paths in the gateway url

- commands/build.go
- stack/schema.go
We need to support supplying build args via the .
This PR allows passing the Docker build arguments to build process using YAML stack file. The new yaml structure will look like:
```
version: 1
provider:
name: openfaas
functions:
url-ping:
lang: python
handler: ./sample/url-ping
image: alexellis2/faas-urlping
build_config:
build_args: # would be translated to the docker --build-args flags during the docker build
GO_MOD: 1
```
To ensure reproducible and portable builds, we should support supplying build args via the YAML stack file.
Resolves: #687
- I have run the included unit tests
- Build `faas-cli` locally on Ubuntu 18.04.4 machine and then done build and deploy for a function with stack.yml structure similar to the one mentioned above in description
> Provide --build-args for functions in stack.yml

- commands/generate.go
- commands/generate_test.go
- proxy/function_store.go
- proxy/function_store_test.go
Looks like the store json is different to the expected structure in the
cli for generating the yaml spec from the function store definitions.
There was a missing wrapper sruct that took the version and the list of
functions.
This has been tested with go build && ./faas-cli generate --from-store
nodeinfo
This generated yaml when there was an error before
Signed-off-by: Alistair Hey <alistair@heyal.co.uk>
Fixes #792 
This has been tested with go build && ./faas-cli generate --from-store
nodeinfo
This generated yaml when there was an error before
> Update struct for OpenFaaS Function store

- commands/remove.go
- proxy/delete.go
- proxy/delete_test.go
This commit Fixes #748. It creates and returns an error when there is a 
HTTP error with the cli remove command and so a non zero exit code (1) is 
returned.
Currently an exit code of 0 is returned for all cases even when there
is a HTTP error with the `faas-cli remove` command in cases where 
there the function does not exist or where a bad gateway is used.
This Fixes #748 and is required to prevent false positives during 
integration testing.
`faas-cli remove invalid-function`
`echo $?`
> Remove returns non zero exit code for HTTP error

- proxy/client.go
- Swtich from `filepath` to the plain `path.Join` when constructing
request URLs because `filepath` is OS aware and uses a different
separator on Windows, which means it constructs invalid URLS
Resolves #805
Change is covered by existing unit test
> Use path instead of filepath for url building

- Gopkg.lock
- commands/deploy.go
- commands/priority.go
- commands/priority_test.go
Signed-off-by: Utsav Anand <utsavanand2@gmail.com>
This commit fixes a namespace issue, where the value passed into
the namespace flag was being ignored if a stack.yaml had a namespace field.
Issue #742 
The output of the newly added test:
```
Running tool: /usr/local/opt/go/libexec/bin/go test -timeout 30s github.com/openfaas/faas-cli/commands -run ^(Test_overrideFlag_deployToNamespace)$
ok  	github.com/openfaas/faas-cli/commands	(cached)
Success: Tests passed.
```
> Override the stack.yaml namespace field from faas-cli. Fixes #742

- commands/remove.go
- Use `getNamespace` utility during the `remove` command to ensure
that the namespace is set correctly and respects the stack file
#811 
Manually tested with KinD and arkade
```yaml
provider:
name: openfaas
functions:
stronghash:
skip_build: true
image: functions/alpine:latest
fprocess: "sha512sum"
namespace: foo
```
```sh
$ kind create cluster 
$ arkade install openfaas --clusterrole --basic-auth=false
$ kubectl create namespace foo
$ faas-cli deploy -f namespace-stack.yaml
Deploying: stronghash.
URL: http://127.0.0.1:8080/function/stronghash.foo
$ kubectl get po -n foo
NAME                          READY   STATUS …
```
> Ensure delete respects namespace value in stack file

- proxy/scale.go
- proxy/scale_test.go
- proxy/utils.go
Add scale function API call to SDK. 
I am using SDK in faas-idler except scale function all other API used by idler is present in SDK. It will be good to add scale function API call to SDK as well. 
I have tested this on my local by calling the scale function from go application.
> Add scale function API to SDK

- builder/copy.go
- builder/copy_test.go
- Ensure that the CopyFiles will create required missing intermediate
folders. This allows the copy extra feature to specify a folder
nested inside several folders, instead of needing to always
specify the parent folder. When copying folders, the CopyFiles
already handles the creation of intermediate folders, this patch makes
behavior consistent.
Resolves #827 
1. A new unit test was added. 
2. I manually tested the copy behavior using `faas-cli build --shrinkwrap`
```yaml
#stack.yaml
provider:
name: openfaas
configuration:
copy:
- ./common
- ./extras/special.txt
functions:
echo-common:
lang: Dockerfile
handler: ./echo-common
fprocess: python index.py
image: theaxer/echo-common
environment:
write_debug: true
```
```sh
➜  faas-cli build --shrinkwrap
[0] > …
```
> Support copying specific extra files

- README.md
- builder/build.go
- config/config_file.go
Signed-off-by: Utsav Anand <utsavanand2@gmail.com>
This PR will enable users of faas-cli, especially the containerised version to have more permissive rules for artefacts created by the CLI to be shared across multiple users, which is typically the case in a CI/CD environment.
Setting the env var CI to true or 1 will make the artefacts created by `faas-cli login` and `faas-cli build` to have 0777 permissions, with the files being created in the current directory, this will make sure the build and login artefacts can be shared across the host OS and user and the container in environments like GitHub Actions where only some host directories like the working dir are mounted to the container. But other environments like Google Cloud Build will benefit from the same.
A running sample of the …
> Add CI env check to change dir and file permissions of artifcats

- commands/generate.go
- schema/openfaas/v1/crd.go
Changing api version in generate command since it was
outdated v1alpha2. The following changes took place:
* duplicated v1alpha2 package to v1 to avoid confusion
* updated examples to point to the right version
* updated default value to be v1 instead of v1alpha2
* fixed a bug where default namespace is unset
The generate command could not properly transform `stack.yml` into crd. Also the default values were missing `openfaas-fn` as default namespace so the functions were deployed in the kubernetes' default namespace.
```
kubectl apply -f something.yaml 
error: unable to recognize "something.yaml": no matches for kind "Function" in version "openfaas.com/v1alpha2"
```
ran `faas-cli generate` to see variables have now default namespace set to …
> Change api version in generate command

- README.md
- config/config_file.go
- config/config_file_test.go
- Support configuration the faas-cli configuration directory path via
the `OPENFAAS_CONFIG` env variable. When this value is set, the path
will be overridden. When empty, we will also check the CI flag, which
defaults the location to the current working directory. When neither
`OPENFAAS_CONFIG` or `CI` are set, then the default location is in
the current HOME folder.
- Various tests have been updated to use this new env variable instead
of modifying the global variables. Also, the variables are now
constants to prevent this kind of modification in general.
Resolves #832 
New unit tests verify the behavior. This is also verified by the modifications to the previous unit tests.
> Allow configuration of CLI config via env variables

- README.md
- builder/build.go
- builder/build_test.go
- builder/publish.go
- commands/build.go
- commands/publish.go
- go.mod
- go.sum
- stack/schema.go
Add publish command to publish multi-arch images
The publish command can be used to build and push a multi-arc image with
Docker buildx and buildkit. A multi-arch template must be used which
a Dockerfile that accepts TARGET/BUILDPLATFORM.
Read more: https://docs.docker.com/docker-for-mac/multi-arch/
Why `publish` instead of updating the existing code?
See details on these issues: #836 #662
Fixes:  #836 #662 
Adding a new command with a single purpose reduces the risk of regression in the core openfaas workflow and commands.
For local dev/test, use faas-cli up.
For CI use `faas-cli publish` followed by `faas-cli deploy`
Tested with the golang-middleware template.
The resulting image worked fine on RPi and Docker Desktop.
``` …
```
> Add publish command to publish multi-arch images

- commands/fetch_templates.go
- commands/fetch_templates_test.go
- versioncontrol/git.go
- versioncontrol/parse.go
- versioncontrol/parse_test.go
**What**
- Use the git server's default remote branch when the template repo
refName is empty. This allows us to support _any_ default branch
instead of the previously hard coded `master`
Discussed on the Wedensday call
I created a new copy of the original templates, but using the default branch `main`: https://github.com/LucasRoesler/templates-main
I then tested the CLI locally using 
```sh
➜ faas-cli template pull https://github.com/LucasRoesler/templates-main
Fetch templates from repository: https://github.com/LucasRoesler/templates-main at 
2020/11/28 18:24:49 Attempting to expand templates from https://github.com/LucasRoesler/templates-main
2020/11/28 18:24:50 Fetched 12 template(s) : [csharp dockerfile go java11 java11-vert-x node node12 php7 python python3 python3-debian ruby] from …
```
> Allow using any default branch name for template repos

- Dockerfile.redist
Signed-off-by: Utsav Anand <utsavanand2@gmail.com>
Leverage buildx to generate binaries in parallel
Use buildx to compile the faas-cli binaries for multiple environments in parallel.
See the build logs [here](https://github.com/utsavanand2/faas-cli/runs/1438473548?check_suite_focus=true)
> Leverage buildx to generate binaries in parallel

- .github/workflows/build.yaml
Signed-off-by: Utsav Anand <utsavanand2@gmail.com>
Test building multi-arch images in CI stage for testing.
Check the build logs [here](https://github.com/utsavanand2/faas-cli/runs/1412905346?check_suite_focus=true)
> Test build multi-arch image in CI builds

- Dockerfile
- Dockerfile.redist
Bump Go version to 1.15
Regular updates to sync with stable Go version.
Testing via CI
> Bump Go version to 1.15

- commands/version.go
- commands/version_test.go
Error checking when nil is returned from the gateway (when commit is not set for example)
https://github.com/openfaas/faas/pull/1606/checks?check_run_id=1539136025
Breaking unit test written, then code changed to fix
> Fix type conversion in gateway version on nil

- commands/secret_create.go
- commands/secret_update.go
- Add flag `--trim` with default value `true`. This allows the user to
control if whitespace is trimmed from the start and end of the secret
value. This can be useful if the secret values format requires
trailing newlines. The default value of `true` preserves backwards
compatibility
Resolves #859
Manually tested locally
```sh
➜  ~ kind create cluster
➜  ~ arkade install openfaas -a=false
➜  ~ faas-cli secret create foo
Reading from STDIN - hit (Control + D) to stop.
a
b
c
Creating secret: foo
Created: 202 Accepted
➜  ~ kubectl get secret -n openfaas-fn foo -o jsonpath="{.data.foo}" | base64 --decode
a
b
c% 
➜  ~ faas-cli secret create bar --trim=false
Reading from STDIN - …
```
> Add flag to control trimming of secrets

- commands/errors.go
- commands/errors_test.go
- commands/login.go
Don't warn about insecure connections to localhost
This message isn't strictly required or beneficial when
connecting to 127.0.0.1 or localhost, where certificates from
Let's Encrypt are not applicable. If using Kubernetes or SSH
port forwarding, then the connection is encrypted already.
The warning message has been updated since SSL is not
applicable to HTTPS currently.
Tested by creating an SSH tunnel to a faasd instance, and
seeing no warning, then connecting to the same faasd instance
with its IP addresses, and continuing to see the error.
The unit tests have been updated to account for the change 
in behaviour wrt: localhost/127.0.0.1
> Don't warn about insecure connections to localhost

- commands/version.go
- commands/version_test.go
- proxy/version.go
- vendor/github.com/openfaas/faas/gateway/types/handler_set.go
- vendor/github.com/openfaas/faas/gateway/types/inforequest.go
- vendor/github.com/openfaas/faas/gateway/types/proxy_client.go
- vendor/github.com/openfaas/faas/gateway/types/readconfig.go
- vendor/modules.txt
This updates the GetSystemInfo API to return typed struct rather than `map[string]interface{}`
It also removes support for legacy vesion info response from gateway which are available prior to version
0.8.4
Fixes: #796
Tested on my local cluster
```
./faas-cli version
|_|
CLI:
commit:
version: dev
Handling connection for 8080
Gateway
uri:     http://127.0.0.1:8080
version: dev
sha:
Provider
name:          faas-netes
orchestration: kubernetes
version:       dev
sha:           819837dcf72d399d54650a30885a7f7074f49b0a
```
> Update GetSystemInfo API return type

- commands/generate.go
- commands/generate_test.go
- commands/priority.go
- commands/priority_test.go
A user deployed to Okteto where the namespace by default is their username.  By forcing openfaas-fn by default this was preventing a zero value from being passed which had the effect of always over-riding the users default namespace.
Fixes #869 
* Created a k8s cluster on DO.
* Created new namespaces (rgee0 & test)
* Set direct_functions_suffix=rgee0.svc.cluster.local & function_namespace=rgee0
```
$ kubectl describe deploy/gateway -n openfaas                                    
Name:                   gateway
Namespace:              openfaas
CreationTimestamp:      Thu, 11 Mar 2021 18:08:05 +0000
Labels:                 app=openfaas
app.kubernetes.io/managed-by=Helm
chart=openfaas-7.2.2
component=gateway
heritage=Helm …
```
> Remove "openfaas-fn" as default namespace

- commands/build.go
- commands/publish.go
- commands/template_pull_stack.go
- commands/template_pull_stack_test.go
Signed-off-by: Nitishkumar Singh <nitishkumarsingh71@gmail.com>
Build and Publish command will not pull templates which are already available in filesystem.
A utility function is included before `pullStackTemplates` to filter the templates which are already available in filesystem. So only the new templates will be downloaded at the time of build and push.
Close #759 
Testing is done on Ubuntu
1. Created a new template using `faas-cli new --lang go fn1`
2. Screenshot of yml and modified time for templates directory in filesystem
3.  Changed yml to included more template. Screenshot for yml and modified time of templates directory is attached.
> Skip already existing templates while build and publish

- schema/image.go
- schema/image_test.go
Fixes the issue described in https://github.com/openfaas/faas-cli/issues/875
Fixes: https://github.com/openfaas/faas-cli/issues/875
Build this PR, and you can follow the steps described in the issue https://github.com/openfaas/faas-cli/issues/875
```
$ faas-cli build --tag sha --image foo:1234/bar --handler ./foo --name foo --lang go
....
#29 writing image sha256:3010593902cbc6c65947e710e240e4f40f25533b5721628a94a25a4a2313245b done
#29 naming to foo:1234/bar:latest-a26c44e done
#29 DONE 0.0s
Image: foo:1234/bar:latest-a26c44e built.
```
cc @alexellis
> build: fix image name when having the case foo:1234/bar

- commands/generate.go
- commands/generate_test.go
This change seeks to introduce a pre-processing stage where a slice of function names is created and a rudimentary sort applied. This slice is then used to iterate through the map using the function name.
The output from faas-cli generate is not deterministic.  The function detail is stored in a map which is by design non-deterministic.
This behaviour is undesirable as generating from the same stack will result in a different output, hence makes tracking diffs, particularly in git, quite a challenge.
Fixes #777
Previous mode of operation is described in https://github.com/openfaas/faas-cli/issues/777#issuecomment-797420368.  The following is provided as a comparison.
```
$ faas-cli version
/ …
```
> Add sort order to generate command

- README.md
- commands/generate.go
- commands/generate_test.go
- schema/openfaas/v1/crd.go
- stack.yml
Add annotations to generated OpenFaaS Custom Resources
Fixes: #890 
A new unit test was added for when an annotation is present, a new binary was built and produced the following output for `./faas-cli generate --filter url-ping`:
```yaml
---
apiVersion: openfaas.com/v1
kind: Function
metadata:
name: url-ping
spec:
name: url-ping
image: alexellis/faas-url-ping:0.2
environment:
debug: "true"
labels:
com.openfaas: "1"
annotations:
test: "true"
```
> Add annotations to generated OpenFaaS CRs

- commands/secret_create.go
- go.mod
- go.sum
- vendor/github.com/openfaas/faas-provider/types/model.go
- vendor/modules.txt
Create files as secrets in binary format
The `--trim=false` flag option was added to allow users to provide files and have them uploaded verbatim, but it seems that the faas-netes handlers still converted all inputs to strings.
This change creates files as binary through the RawValue field, and is backwards compatible since the Value field is also populated.
Tested e2e through and the file was accepted by my function, which failed previously.
```bash
/home/alex/go/src/github.com/openfaas/faas-cli/faas-cli secret create astra-secure-connect --from-file ./astra-secure-connect.zip
```
> Create files as secrets in binary format

- commands/generate.go
Signed-off-by: Yankee Maharjan <yankee.exe@gmail.com>
Addresses #894 
Show help message when no flags are passed (`--yaml` or `--from-store`) and no `stack.yml` file is present in the current working directory.
Currently the CLI returns no result, confusing user what happened. Showing help message will guide the user to take corrective actions for the `generate` command.
run the command below with no flags and no `stack.yml` file in current working directory.
```bash 
go run . generate
```
> Show help message with no stack file and flags

- commands/generate.go
Add `defaultFunctionNamespace` to avoid empty namespace on Kubernetes CRD YAML generation.
Resolves #892
Signed-off-by: Yankee Maharjan <yankee.exe@gmail.com>
Generates CRD YAML file with default namespace (`openfaas-fn`) if not provided.
Generate YAML config with default namespace:
> Add the openfaas-fn namespace to function store Custom Resources

- commands/describe.go
When the Labels were empty they would appear on the same line as the Annotations.
Signed-off-by: Haris Razis <haris@razis.com>
A new function was created, that handles both Labels and Annotations. <none> is printed when no labels exist.
#900 
- 1 annotation and no labels
```
➜ faas-cli describe figlet-1              
Name:                figlet-1
Replicas:            1
Available replicas:  1
Invocations:         0
Image:               
Function process:    figlet
URL:                 http://10.40.98.209:8080/function/figlet-1
Async URL:           http://10.40.98.209:8080/async-function/figlet-1
Labels               <none>
Annotations          person : xrazis
```
- 0 annotations and 1 label
```
➜ faas-cli describe figlet-2              
Name: …
```
> Fix describe command formatting

- Dockerfile
- LICENSE
- README.md
- commands/auth.go
- commands/auth_test.go
Support PKCE for auth command for OpenFaaS Pro users
The implicit flow is considered insecure, PKCE takes its place.
* Enables PKCE in the place of implicit auth flow.
* Auth command requires EULA acceptance and valid OpenFaaS Pro
license or trial.
* Updates feature status from alpha to generally-available
Tested with Auth0 using a Web Application that I created. The token is saved into the local cache for re-use.
I also generated an error on purpose to check for error handling. 
I've updated the LICENSE for new portions of code that are licensed under the OpenFaaS Pro EULA and am changing the OpenFaaS docs to mention the code flow should be used instead of implicit.
> Support PKCE for auth command for OpenFaaS Pro users

- commands/describe.go
- commands/describe_test.go
- schema/describe.go
Add the function
* constraints
* environment variables
* secrets
* requests and limits
to the `faas-cli describe` output.
Resolves #913 
Create a test cluster using KinD
```sh
kind create cluster --config=cluster.yaml
arkade install openfaas -a=false --function-pull-policy=IfNotPresent --wait
faas-cli store deploy nodeinfo --annotation sample=true --label status=418
```
Now deploy a sample function
```sh
$ faas-cli describe nodeinfo
Name:                nodeinfo
Replicas:            1
Available replicas:  1
Invocations:         0
Image:               ghcr.io/openfaas/nodeinfo:latest
Function process:    <default>
URL:                 http://127.0.0.1:8080/function/nodeinfo
Async URL:           http://127.0.0.1:8080/async-function/nodeinfo
Labels …
```
> feat: Add missing fields to the describe output

- Dockerfile
- Dockerfile.redist
- commands/deploy.go
- commands/store_deploy.go
- sample/imagemagick/Dockerfile
Upgrade to Go 1.18 and introduce timeout for deploy
* Go is upgraded to 1.18 for builds
* Alpine Linux is upgraded for the runtime container
* The deploy command gains a timeout for use with faaasd
which is synchronous and would time-out otherwise.
I couldn't deploy a large > 1GB image to faasd, since it has a hard-coded timeout of 60s.
```
ubuntu@ubuntu:~/imagenet-openfaas$ faas-cli deploy
Deploying: imagenet.
Is OpenFaaS deployed? Do you need to specify the --gateway flag?
Post "http://127.0.0.1:8080/system/functions": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
Function 'imagenet' failed to deploy with status code: 500
```
The CLI flag `--timeout` was added, and I may mention this in …
> Upgrade to Go 1.18 and introduce timeout for deploy

- commands/generate.go
- commands/generate_test.go
- schema/openfaas/v1/crd.go
Signed-off-by: Han Verstraete (OpenFaaS Ltd) <han@openfaas.com>
Make sure the readonly_root_filesystem setting is included in the resulting CRD when running `faas-cli generate`.
Closes #928 
1. Verified output of generate command
Stack.yml:
```yaml
version: 1.0
provider:
name: openfaas
functions:
python3-http-fn:
lang: python3-http
handler: ./python3-http-fn
image: welteki2/python3-http-fn:latest
readonly_root_filesystem: true
```
Generated CRD:
```yaml
---
apiVersion: openfaas.com/v1
kind: Function
metadata:
name: python3-http-fn
namespace: openfaas-fn
spec:
name: python3-http-fn
image: welteki2/python3-http-fn:latest
readOnlyRootFilesystem: true
```
> Fix generate command for read-only root filesystem setting

- commands/describe.go
- commands/describe_test.go
As `describe` uses a map to store the env var kv pairs its output varies in its ordering.  This is undesirable.
This change introduces a means by which env var output ordering is predictable.
Wrote a test that will intermittently fail because of the env var order changing
Pushed the commit and observed CI output:
https://github.com/openfaas/faas-cli/actions/runs/3119630183/jobs/5059713636#step:6:6018
After adding the required code....
Created a multipass ubuntu vm and installed faasd
Deployed env from the store using:
```
faas-cli store deploy env  --gateway http://<IP-ADDRESS>:8080 -e FRED=fred -e BURT=burt -e RICH=rich -e ALEX=alex
```
Ran watch with the current `faas-cli` version:
```
faas-cli version
___                   _____ …
```
> Make envVar output from describe deterministic

- proxy/client.go
- version/version.go
The code already existed for setting the UserAgent header, but a value was never passed to the client. This change will now set a string matching the following format
```
faas-cli/<build version>
```
For example:
```
faas-cli/0.14.6-5-ga9c2b10f
```
The missing user agent was noticed in my nginx access logs while debugging a function today 
Manually tested in the same environment as before, i now see `faas-cli/<version>` in the access logs
> fix: set the client user agent

- commands/registry_login.go
Signed-off-by: Han Verstraete (OpenFaaS Ltd) <han@openfaas.com>
Fix registry-login command for ecr:
Running the command with the --ecr flag always fails because it checks if other flags are not set and some have default values.
Ignore these flags instead of exiting when they are provided.
Fix flag validation for registry-login command.
Verified flag validation for the command works as expected:
> Fix registry-login command for ecr

- .gitignore
- commands/deploy.go
- commands/local_run.go
- commands/update_gitignore.go
- commands/update_gitignore_test.go
- stack.yml
Improve the DX by simplifying the process to run a functional locally. This makes it easier to quickly build and test a function.
For simplicity, this only supports running functions defined in stack files.
1. First install using `make local-install`
2. Then attempt to run a function using these commands
a) basic operations that don't run a container
```sh
faas-cli run --help
faas-cli run stronghash --print
```
b) very simple function spec
```sh
faas-cli template store pull python 
faas-cli build --filter 'url-ping'
faas-cli run url-ping
```
now in a new terminal
```sh
$ curl -XPOST localhost:8080 -d "foo"
Handle this -> foo
Give me a URL and I'll ping it for you.
$ curl -XPOST localhost:8080 -d "https://google.com"
Handle this -> https://google.com
```
c) function that requires a secret …
> feat: add run command for local testing

- README.md
- commands/local_run.go
- commands/plugin_get.go
Local run improvements for developer experience
When there is only one function within the YAML file, run that instead of prompting for a name
Print the address for the local web server.
Improved examples and help text for the command within the CLI.
Tested whilst building a Discord bot and demonstrated on the weekly office hours call
> Local run improvements

- commands/local_run.go
Signed-off-by: Han Verstraete (OpenFaaS Ltd) <han@openfaas.com>
Reintroduce gitignore update in local-run.
Accidentally removed in #950.
Reintroduce accidentally removed functionality.
Verified the `.gitignore` file is created or updated when running `faas-cli local-run`
> Reintroduce gitignore update in local-run

- commands/generate.go
- commands/generate_test.go
- config/config_file.go
Add fprocess to generated CRDs and fix indentation
Indentation changed to four spaces when upgrading to the v3 YAML paser, this reverts to 2 spaces.
The fprocess variable in the store was missing from generated function YAML files with faas-cli generate --from-store - this has now been fixed and an env will be emitted when there is no existing conflicting definition in the store's manifest.
Tested before/after - env now can be deployed, previously it couldn't be.
Before:
```sh
faas-cli generate --from-store env
---
apiVersion: openfaas.com/v1
kind: Function
metadata:
name: env
namespace: openfaas-fn
spec:
name: env
image: ghcr.io/openfaas/alpine:latest
labels: {}
annotations: {}
```
After:
```sh
go run . generate --from-store env
---
apiVersion: openfaas.com/v1
kind: Function
metadata: …
```
> Add fprocess to generated CRDs and fix indentation

- commands/local_run.go
This PR adds a new flag `build` for `local-run` command. If the value of the `build` flag is set to `true`(default) then the function is built before `local-run`.
- Fixes: #953
I have tested the new command locally and it works as expected.
- With `--build=false`, `local-run` command does not reflect the new changes made in the funtion.
- With `--build=true` it is not the case, the changes are reflected in the run, since `build` command logic is being executed before each `local-run`.
> Add new build flag for local-run command

- builder/build.go
- builder/publish.go
- commands/build.go
- commands/publish.go
- commands/up.go
- go.mod
- go.sum
- vendor/github.com/alexellis/hmac/v2/LICENSE
- vendor/github.com/alexellis/hmac/v2/README.md
- vendor/github.com/alexellis/hmac/v2/pkg.go
- vendor/modules.txt
This PR works on adding the new `remote-builder` flag for faas-cli to be able to perform build operations from Function Builder API in Openfaas Pro. A new `payload-secret` flag is also added, in which the path of the payload.txt file containing the payload secret is specified.
**Demo's** : 
-  **Basic command** : https://asciinema.org/a/LKpTzW0FhfoqHqbJKmIzkmcK1
- **Building 6 functions, 2 in parallel** : https://asciinema.org/a/DZYpO2oQ7FbNvjoUCaTw3vtb1
- **Up command with remote-builder** : https://asciinema.org/a/No1XmpjK6Fr7fXkYaBV4z1tNn
- **With Build Args** : https://asciinema.org/a/vJPPSqm3GytD51M7wOC3lJvOT
Fixes: https://github.com/openfaas/faas-cli/issues/931
- publish command with `--remote-builder` flag is successfully run
```
> faas-cli publish --remote-builder …
```
> add new remote-builder flag to build with the Function Builder API through faas-cli

- builder/build.go
- commands/local_run.go
- commands/up.go
Fixes for the --watch flag for faas-cli up due to incomplete / defective feature PR.
* Fixes issue where all functions are rebuilt even if only one changed
* Fixes issue where unrelated files cause rebuilds
* Fixes issue where vim can't trigger and update due to using create
* Adds newly created folders into the watch when within a function's path
* Triggers rebuilds via stack.yml
Fixes: #968
Tested with:
* creating a new folder within a function's handler
* editing a function's code multiple times with vim
* editing the stack.yml file
* `faas-cli new --append` during a watch
* two functions, only the changed one is rebuilt
* Out of scope for this PR - "copy extra directories" that can be specified for each function
> Fixes for the --watch flag for faas-cli up

- commands/build.go
- commands/local_run.go
- commands/up.go
- commands/watch.go
Implement --watch for localrun with cancellation support
Related to fixes in #969 which were for `faas-cli up --watch`
This commit adds --watch support to localrun by using a context to cancel and remove any running container when a change is detected.
watchLoop has been updated to support a context.
Tested with VSCode - I suggest turning auto-save off when using this feature.
Tested again with faas-cli up to make sure there was no regression:
https://asciinema.org/a/594072
> Implement --watch for localrun with cancellation support

- commands/publish.go
The examples for the publish command showed a wrong flag `--remote-address` instead of `--remote-builder`. This PR fixes that error.
Use the correct flag in the examples. Discovered by Alex during a demo on the community call.
Run `faas-cli publish --help` to verify the example is correct.
> Fix remote-builder flag example

- versioncontrol/git.go
Explicitly set default init branch when creating repos.
Prevent tests from failing on systems that are configured to use an other default branch than master.
Fixes #978
Before this fix unit tests where failing on both my Mac an Ubuntu workstation. They are all passing now.
> Explicitly set default init branch when creating repos

- commands/deploy.go
- commands/store_deploy.go
Add memory/CPU requests and limits to deploy command
* Allows for memory/CPU requests and limits to be passed via deploy and store deploy when no additional YAML file is being used.
Tested by supplying requests values and looking at the output of faas-cli describe.
Removing the flags removed the values from the function.
> Add memory/CPU requests and limits to deploy command

- commands/faas.go
- commands/plugin_get.go
- syscall.Exec is not supported on Windows systems. Use the os/exec package instead.
- On windows the plugin executables should have the .exe filename extension in order to execute them.
Executing plugins on Windows failed with the error `Error from plugin: not supported by windows`.
- Verified `faas-cli plugin get pro` works on windows and stores the executable in the correct path `$HOME/,openfaas/plugins/pro.exe`
- Verified `faas-cli plugin get pro` still works Linux systems.
- Verified running plugins works on Windows systems.
- Verified running plugins still works on Linux systems.
> Fix execution of plugins on Windows

- builder/build.go
- builder/build_test.go
- builder/publish.go
Simplify the signature of `createBuildContext` and export the function so that it can be used by other packages.
Usage example:
```go
import (
"log"
"github.com/openfaas/faas-cli/builder"
"github.com/openfaas/faas-cli/stack"
)
handler := "./hello-world"
lang := "node20"
fnName := "hello-world"
template, err := stack.LoadLanguageTemplate(handler)
if err != nil {
log.Fatal(err)
}
buildContext, err := builder.CreateBuildContext(fnName,  handler, template, []string{})
if err != nil {
log.Fatal(err)
}
```
Expose more of the builder functionality use outside of the faas-cli. This change was primarily made for OpenFaaS users that want to integration with the Function Builder API to allow them to easily create the function build context from go code.
- Verified the `faas-cli build` and `faas-cli` …
> Export CreateBuildContext function from the builder package.

- builder/build.go
- builder/build_test.go
- builder/publish.go
Fix nil pointer dereference when getting the build options packages.
Fixes #1001 
- Verified the `faas-cli up` command works for function using the dockerfile template.
> Revert changes to createBuildContext to fix #1001

- README.md
- build_integration_test.sh
- builder/build.go
- builder/copy_test.go
- builder/publish.go
- commands/build.go
- commands/deploy.go
- commands/faas.go
- commands/faas_test.go
- commands/fetch_templates.go
- commands/fetch_templates_test.go
- commands/generate_test.go
- commands/new_function.go
- commands/new_function_test.go
- commands/plugin_get.go
- commands/publish.go
- commands/registry_login.go
- commands/template_pull.go
- commands/template_pull_stack.go
- commands/template_pull_stack_test.go
- commands/template_store_list.go
- config/config_file.go
- config/config_file_test.go
Pull templates from store when not present
Implements a user-experience changes:
faas-cli new - when the templates folder is not present the language will be looked up in the template store using the default URL or an overriden one.
faas-cli publish - when no template folder is available then a pull will be carried out if a configuration section is present with a template given within in
Filtering - whilst there is no way to avoid pulling all the templates wihtin a repository, only the requested/needed ones are expanded by commands like faas-cli new.
Improve user experience as discussed on community call Jan 22 2025
Tested mainly with existing-unit tests, faas-cli new / publish with and without a templates folder.
> Pull templates from store when not present

- commands/invoke.go
- commands/invoke_test.go
Change the header flag to accept key value pairs separated by a colon. e.g. "key: value".
The previous format is marked as deprecated but still supported. A warning is printed when it is used.
Fix an issues where the 'Content-Type' header was being overridden by the default value of the `--content-type` flag when the flag is not set explicitly.
e.g. when running `faas-cli invoke -H "Content-Type=application/tar"` the content type would be overridden with the default value `text/plain`.
Align the format more closely with `curl` to make the invoke command as intuitive and familiar as possible.
Changes are covered by unit test.
Verify headers can be set using the new format:
```sh
faas-cli invoke -H "foo: bar" <<< hello
```
Verify the deprecated format is still accepted and prints a warning: …
> Use same header format as curl for invoke command
