README.md
app.go
schema.go
test.yml

See updates to README file for usage.

Support YAML

---

app.go
build_redist.sh
sample/ruby-echo/Gemfile
sample/ruby-echo/handler.rb
samples.yml
schema.go
template/ruby/Dockerfile
template/ruby/Gemfile
template/ruby/function/Gemfile
template/ruby/function/handler.rb
template/ruby/index.rb

Basic Ruby template
Now has gem support via Gemfile.

Add Ruby template

---

app.go
fetchTemplates.go

Restoring behaviour lost during prior merge.

Restore pulling templates behaviour

---

template/node-armhf/Dockerfile
template/python-armhf/Dockerfile

These files allow the faas-cli to be used on armhf.

Add ARM dockerfiles

---

app.go

Enable `-action delete`
Community suggestion to delete functions once deployed.
* By deleting a named function
* By deploying from the YAML samples and then deleting with the stack file via `-f`

Enable -delete as an action

---

app.go
build_samples.sh
builder/build.go
builder/exec.go
fetchTemplates.go
proxy/delete.go
proxy/deploy.go
stack/schema.go
stack/stack.go

app.go exploded out into logical groupings
* proxy - remote calls
* builder - invoking Docker CLI to do builds
* stack - schema and YAML parsing
#43 
Tested through deploy/build/push and delete with local stack + FaaS. Docker for Mac.

Refactor app.go into packages/files

---

.gitignore
Dockerfile
Dockerfile.redist

Update to Golang 1.8.3 for Docker build and redist binaries 
Tested on Darwin, Linux + armhf

Update to Golang 1.8.3

---

builder/build.go
sample/imagemagick/Dockerfile
samples.yml

* If can't use or edit a language template - then Dockerfile will build from the "handler" directory directly. There is no reason to copy to a temporary "build" folder.
* Converts imagemagick to a sample which is built as a "Dockerfile" language
Changed from "Custom" to "Dockerfile" after discussion on Slack / GitHub. #29 
* Using invalid "handler" path triggers validation
* Updated samples and to create new imagemagick example - instead of pre-built image previously in the samples.

Allow Dockerfile language

---

CONTRIBUTING.md
builder/build.go
builder/exec.go
fetchTemplates.go
proxy/delete.go
proxy/deploy.go
stack/schema.go
stack/stack.go
template/csharp/Program.cs
template/node/index.js
template/python/index.py
template/ruby/index.rb

* Broke out several new files for refactoring - needed to have MIT header added.
* Contribution guide is to be used from main FaaS repo - this is referenced, but have explicitly re-iterated the DCO.

Merge header notice from MIT to newly refactored files

---

.travis.yml

This commit updates Travis to build `faas-cli` for all target platforms
and deploy the resulting binaries to Github whenever a release is
tagged.
**NOTE** the `api_key` will need to be populated with a travis secure
encrypted copy of a Github token with repo access.
- Create a personal token for the faas-cli deploy with `repo:status`,
`repo_deployment`, `public_repo` scope
- Encrypt that token with the travis cli.
```
sudo gem install travis -v 1.8.8 --no-rdoc --no-ri
cd $GOPATH/src/github.com/alexellis/faas-cli/
travis login
travis encrypt YOUR_GITHUB_TOKEN
```
- Replace `ADD SECURE TOKEN HERE` with your generated secure token inside the quotes.
Have run the process on a test repo - https://github.com/johnmccabe/delmeee/releases/tag/0.0.2-alpha

Build and deploy all platforms to Github on tag - fixes #67

---

commands/deploy.go
commands/faas.go
commands/invoke.go
commands/list.go
commands/new_function.go
commands/remove.go

Use constant for default gateway strings

---

Dockerfile
Dockerfile.redist
commands/version.go
commands/version_test.go
test/version.sh

Expected behavior
```
$ ./faas-cli-darwin version
|_|
Commit: a2dd47165dc32c8d2167af155a89ab5f616b27cc
Version: dev (or tag)
```

Add tag into version command and shorten SHA1

---

README.md
commands/deploy.go
stack/schema.go

Allow environmental variables to be defined in an external file
Lowers risk of inadvertently committing secrets to Git.
Tested with sample app and config:
env_files.yml
```
provider:
name: faas
gateway: http://localhost:8080
functions:
env_files:
lang: node
handler: ./env_files
image: env_files
environment:
url: http://hyper.sh
secret_key: lolz
environment_file:
- ./login.yml
- ./urls.yml
```
login1.yml
```
environment:
account: alex.ellis
secret_key: dogfight
```
urls.yml
```
environment:
url: https://hyper.sh
post_back: https://b.z.y
```
handler.js
```
"use strict"
module.exports = (context, callback) => {
callback(undefined, process.env);
}
```
Sample function prints a map of environmental variables:
```
account: 'alex.ellis',
post_back: …
```

Allow environment_file in YAML files

---

commands/deploy.go
proxy/deploy.go

Add update flag for existing deployments
Usage:
```
$ faas-cli deploy -f samples.yml --update --replace false
```
Currently supported by K8s provider.

Add update flag for existing deployments

---

commands/build.go

Merges parallel builds for the CLI
> Note: Can't remember if this change was merged @rgee0 @itscaro or whether we tested with the branch?

Parallel build functionality

---

commands/list.go

This change adds the `ls` alias for the `faas-cli list` command.
I feel that these changes make hacking on OpenFaaS just a bit faster, and require very little code change, so it might be worth it to include them in the build.
Adds the `ls` alias to `faas-cli list` command.
Typing the full `faas-cli list` command can be tedious, so this may help reduce the time it takes to iterate.
#122

Add `ls` alias for `faas-cli list` command

---

CONTRIBUTING.md
README.md
commands/new_function.go
commands/remove.go
template/csharp/obj/Debug/netcoreapp2.0/root.csproj.CoreCompileInputs.cache

```
faas-cli new --name tester1 --lang python
```
Becomes:
```
faas-cli new tester1 --lang python
```
Dockerfile is allowable as a "lang" type and introduces a folder and helper Dockerfile:
```
faas-cli new tester2 --lang Dockerfile
faas-cli new tester2 --lang dockerfile
```
Issue raised on Slack #contributors 
With existing languages and `Dockerfile` type.
This is a breaking change and requires an edit to documentation mentioning the "new" verb.

Allow un-named parameter for function name and template Dockerfile

---

README.md
commands/invoke.go

- udated read me
- updated invoke command
Signed-off-by: Alexis Rivera DeLa Torre <garivera89@gmail.com>
I updated the cli usage descriptions and readme doc
Altered the way that invoke takes argument to expected state.

Alter-invoke-verb

---

commands/build.go
commands/push.go

Enables --parallel flag for `faas-cli push`

Push in parallel

---

template/node-arm64/index.js
template/node/index.js

Signed-off-by: Finnian Anderson <get@finnian.io>
Replace `console.log` with `process.env.write` for string/data output because `console.log` prettifies the output. This can be a problem when returning things like images from functions.
Replace `console.log` with `process.env.write` in the Node template
`process.stdout` is a drop-in replacement for `console.log` when handing strings so it doesn't have any breaking changes. Tested using this handler:
```js
"use strict"
module.exports = (context, callback) => {
callback(undefined, 'done');
}
```

Replace console.log with process.stdout.write for Node templates

---

README.md

Signed-off-by: Finnian Anderson <get@finnian.io>
Updates the asciinema recording used in the README.
New version shows templating, build & deploy using the new syntax for the CLI (`build` vs `-action build`)

Update asciinema demo

---

commands/version.go

This PR sets the version logo colour to green so as to avoid clashing with the Powershell default blue.
Tested on OSX and Windows 10

Use green logo on windows

---

template/go-armhf/Dockerfile

Golang ARMHF template

---

commands/deploy.go
proxy/deploy.go
vendor/github.com/openfaas/faas/gateway/requests/requests.go

To support secrets and this PR https://github.com/openfaas/faas-netes/pull/54
Pointing at the Kubernetes faas-netesd daemon.

Add named secrets

---

commands/deploy.go
commands/deploy_test.go

Add test coverage to gateway URL overriding
Unit tests and manually with combos as described in unit tests

Add test coverage to gateway URL overriding

---

commands/invoke.go
proxy/invoke.go
proxy/invoke_test.go

Add --query flag to CLI, but not to YAML
Fixes #172

Mile high commit - adds --query flag to CLI, but not to YAML

---

template/node/Dockerfile

Fix breakage by https://github.com/openfaas/faas-cli/pull/83/files

Fix permissions for Node.js

---

.gitignore
README.md
commands/login.go
commands/logout.go
config/file.go
config/file_test.go
proxy/auth.go
proxy/auth_test.go
proxy/delete.go
proxy/deploy.go
proxy/invoke.go
proxy/list.go
vendor.conf
vendor/github.com/mitchellh/go-homedir/LICENSE
vendor/github.com/mitchellh/go-homedir/README.md
vendor/github.com/mitchellh/go-homedir/homedir.go

Restore Stefan as author of commits in Git

---

commands/build_test.go

Signed-off-by: Nenad Ilic <nenadilic84@gmail.com>

build_test: Update the Copyright

---

Dockerfile
Dockerfile.redist

Implements compliance checking for https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md at CI time.
Merge after change is pushed for build_test.go via @nenadilic84

Scan for license compliance during build

---

Dockerfile
Dockerfile.redist
commands/version.go
commands/version_test.go
version/version.go
version/version_test.go

Signed-off-by: Lewis Cowles <lewiscowles@me.com>
See #208 
Separate version from command
Fixes #208 
Tested using build script and manually running `faas-cli version`

Command Version Separation

---

commands/deploy.go
proxy/deploy.go
proxy/deploy_test.go
samples.yml
stack/schema.go
stack/stack.go
vendor/github.com/openfaas/faas/gateway/requests/requests.go

Add Requests / Limits for functions
Enables resources / limits to be defined in YAML - https://github.com/openfaas/faas/pull/385
Via gateway built with - https://github.com/openfaas/faas/pull/385

Backlog: Add Requests / Limits for functions

---

.DEREK.yml

Adds a .DEREK.yml file which is a migration of MAINTAINERS so that the repo can be managed by the latest version of Derek.
Derek is evolving.  This change enables the repo to grow with him.

Adding .DEREK.yml to enable more granular permissions fixes #230

---

commands/faas.go
commands/list_test.go
commands/remove_test.go

Adding some unit tests to the list command
While working on https://github.com/openfaas/faas-cli/issues/183, my previous ticket (https://github.com/openfaas/faas-cli/pull/197) was closed since there was trouble merging it. These tests were all that were left to merge.
- [] I have added tests to cover my changes.

Adding some unit tests to list command

---

commands/deploy.go
stack/schema.go

- Add secrets array property to the stack file schema
- Addresses #227 
- This work supports the other work done in the gateway and faas-netes to provide more secure usage of secrets. 
Tested by deploying a function with a secret value to a dev swarm cluster.

Add secretes array to the stack file schema

---

commands/deploy.go

Merge secrets from CLI arguments and YAML
Update YAML
```
url-ping:
.....
secrets:
- beta_secret
- alpha_secret
```
Then send in parameters:
```
./faas-cli deploy -f samples.yml --filter=url-ping --secret alpha_secret --secret zeta_secret
```
You should see three secrets.

Merge secrets from CLI arguments and YAML

---

commands/login.go

Fix #245
Tested on GKE with TLS Ingress and L7 load balancer

Enable keep alive on login - fix for TLS Ingress (L7 LB)

---

builder/build_test.go
commands/deploy.go
commands/template_pull.go
commands/template_pull_test.go
legacy_cli.go
proxy/invoke.go
proxy/invoke_test.go
stack/stack.go
stack/stack_test.go

error string starts with lowercase and do not contain trailing '.'

---

.travis.yml
Dockerfile
Dockerfile.redist
Makefile

- Golang 1.9.2
- multi-line in Dockerfile for readability
- add `build_samples` in Makefile

Bump Golang 1.9.2

---

Gopkg.lock
Gopkg.toml
commands/faas.go
commands/new_function.go
commands/version.go

PowerShell & Bash in WSL
Debian 9 via Bash in WSL

use docker/pkg/term to correct colored texts on Windows & create a function to print figlet

---

template/python-armhf/Dockerfile
template/python3/Dockerfile

Python3 and python-armhf requirements order changes to support users with an older faas-cli version which uses faas-cli/template to pull sample templates.

changes order of requirement installation for python3 and python-armhf

---

commands/deploy.go

Signed-off-by: Umesh Yadav <umesh4257@gmail.com>
Removed unused function from command/deploy.go
fixes #238 
CC / @alexellis @ericstoekl

Removed unused function.

---

commands/build.go
commands/push.go

Match number of ending message `<` with starting message `>` & color these messages yellow

---

commands/build.go
commands/fetch_templates.go
commands/new_function.go

Append to stack files
#213 
Positive test:
```
$ go build
$ ./faas-cli new --lang go fn1
$ ./faas-cli new --lang go fn2 --append fn1.yml
```
Negative test:
* Gives error on file not existing 
```
$ go build
$ ./faas-cli new --lang go fn1
$ ./faas-cli new --lang go fn3 --append fn2.yml
```
* Gives error since filename isn't .yml or .yaml
```
$ go build
$ ./faas-cli new --lang go fn1
$ ./faas-cli new --lang go fn3 --append fn2.txt
```

Simple append to stack file

---

template/csharp/root.csproj

Updated the csharp template root.csproj to prevent ["globbing"](https://docs.microsoft.com/en-us/dotnet/core/tools/csproj#default-compilation-includes-in-net-core-projects) and compile the function project as a library
Resolves #305 
* Run `faas new tester --lang csharp`
* Run `faas build -f tester.yml`
* Monitor the logs to see there is no warning
* Run `faas deploy -f tester.yml` and ensure the function works as expected

Update the csharp template to match template repo

---

commands/store.go

Rename `-g` to `-u` in `store list` & `store inspect` commands to avoid mistake when using shorthand.
Add `--gateway` `-g` and `handler` to `store deploy`
Remove `--handler` and `--lang` from usage help
```
faas-cli -g localhost:31112 store list
Cannot connect to OpenFaaS store on URL: localhost:31112
```
```
faas-cli store deploy Left-Pad -g 127.0.0.1:31112
Unknown shorthand flag: 'g' in -g
```
```
faas-cli store deploy Left-Pad --gateway 127.0.0.1:31112
Unknown flag: --gateway
```
````
faas-cli fix-gateway-flag *$% = $ .\faas-cli.exe store deploy left-pad -g http://localhost:8080
Deployed. 200 OK.
URL: http://localhost:8080/function/leftpad
```

[Ready to merge] add --gateway to store deploy command & rename shorthand -g to -s for store list and store inspect

---

builder/build.go
commands/build.go
commands/common.go
commands/deploy.go
commands/new_function.go
stack/language_template.go
stack/stack.go
stack/stack_test.go

Convert case internally : Dockerfile to dockerfile

---

commands/deploy.go
commands/store.go
commands/store_deploy.go
commands/store_inspect.go
commands/store_list.go

This PR corrects also: `store deploy` must not consider yaml file
I tested these commands:
* faas-cli store list
* faas-cli store list -u "https://cdn.rawgit.com/openfaas/store/master/store-arm64.json"
* faas-cli store inspect "Tesseract OCR"
* faas-cli store inspect -u "https://cdn.rawgit.com/openfaas/store/master/store-arm64.json" sha512sum
* faas-cli store deploy Figlet -g http://localhost:8081
* faas-cli.exe store deploy "Tesseract OCR" --replace=true --update=false --env=openfaas.label=itscaro
* faas-cli.exe store deploy "Tesseract OCR" --replace=true --update=false

[Need review] Re-factor store commands

---

commands/push.go
commands/push_test.go

Test validation for pushing without a Docker Hub user prefix or remote server address 
https://github.com/openfaas/faas-cli/pull/332
By adding unit tests for positive and negatives cases and locally by failing to provide a prefix then pushing:
```
mini:faas-cli alex$ cd /tmp
mini:tmp alex$ faas new --lang node tester
2018/02/28 14:56:52 No templates found in current directory.
2018/02/28 14:56:52 Attempting to expand templates from https://github.com/openfaas/templates.git
2018/02/28 14:56:54 Fetched 11 template(s) : [csharp dockerfile go go-armhf node node-arm64 node-armhf python python-armhf python3 ruby] from https://github.com/openfaas/templates.git
Folder: tester created.
/ _ \ _ __ …
```

Add tests for push image validation

---

commands/faas.go
commands/new_function.go
commands/new_function_test.go

Signed-off-by: Ken Fukuyama <kenfdev@gmail.com>
This adds a `--prefix | -p` parameter to the `faas new` command.
You can set the prefix for the function image name.
issue #338
```
faas new --lang dockerfile prefixed-func --prefix kenfdev
provider:
name: faas
gateway: http://localhost:8080
functions:
prefixed-func:
lang: dockerfile
handler: ./prefixed-func
image: kenfdev/prefixed-func
```
```
faas new --lang dockerfile shortcut-prefixed-func -p 10.0.95.1:5000
provider:
name: faas
gateway: http://localhost:8080
functions:
shortcut-prefixed-func:
lang: dockerfile
handler: ./shortcut-prefixed-func
image: 10.0.95.1:5000/shortcut-prefixed-func
```
```
faas new --lang dockerfile non-prefixed-func
provider:
name: faas
gateway: http://localhost:8080
functions:
non-prefixed-func:
lang: dockerfile …
```

Added a `prefix` parameter when creating a new function.

---

.DEREK.yml

added viveksyngh as maintainer

---

commands/invoke.go
commands/invoke_test.go
proxy/invoke.go
proxy/invoke_test.go

Add --async/-a flag to invoke subcommand
Invoked against a test endpoint, unit tests added.

Add --async/-a flag to invoke subcommand

---

commands/invoke.go
proxy/invoke.go
proxy/invoke_test.go

[WIP] added --method flag for HTTP request method

---

README.md

Add F# template via @hayer
Proposed template by @hayer for FSharp.
Blocking changes:
#343 
Requires testing

Add F# template via @hayer

---

commands/new_function.go
commands/new_function_test.go

According to YAML spec, YAML keys MUST be unique
http://www.yaml.org/spec/1.2/spec.html section 1.3
This change blocks the new command from creating duplicates when using the append flag
The block happens before the function is created to prevent having a conflict between
the function generated and the function defined in the yaml file
Added check based on function name to the `new --append` command + flag
Moved the append file read function higher in the order to be able to block before the function gets created. 
[Specs](http://www.yaml.org/spec/1.2/spec.html) say YAML keys MUST be unique (section 1.3)
Resolves #354 
Added unit test to the `new_function_test.go` that creates a yml file with a sample function definition and runs the …

Prevent duplicate function when using append flag

---

Dockerfile

Update to use the new license check process.
Including all the possible authors to prevent failing builds from occuring as-is
Resolves #441 
Currently causing PR #439 to fail
Updated the Dockerfile and ran it against the failing PR. Verified the build is now successful
FYI: @LucasRoesler

Update license check to 0.2.2

---

commands/new_function.go
stack/language_template.go
stack/schema.go

This commit updates `faas-cli new` command to print language specific
welcome message by default. It also has a flag `--quiet` or `-q` to
supress the welcome message.
Fixes: #437
Issue raised by @alexellis #437 
I have tested this on my local for the following scenario. 
1. For a template with the welcome message 
```
openfaas /Users/viveks/Repos/go-projects/src/github.com/openfaas/faas-cli/faas-cli new demo1 --lang=go                           
Folder: demo1 created.
|_|
Function created in folder: demo1
Stack file …
```

Updated `faas-cli new` to print welcome message

---

commands/faas.go
commands/version.go
commands/version_test.go
test/utils.go
test/version.sh

Add gateway & provider details to version command  …
1. If available display gateway uri, version, sha and last commit
message
2. Display provider name, orchestration, version and sha
```
$ faas-cli version
|_|
CLI commit: c617c05185a2f6bfc7150f90fe9ad6937f23f9ee
CLI version: dev
- Gateway 
uri: http://127.0.0.1:8080
- Provider 
name: faas-swarm 
orchestration: swarm 
version: 0.3.5 
sha: b8cc399b5eadfb59956b8341a44ea3ba4acf1e7f
```
```
$ faas-cli version
| | | | '_ \ / _ \ '_ \| …
```

Add gateway & provider details to version command

---

stack/schema.go

Updated welcome message field to welcome_message

---

Dockerfile
Dockerfile.redist

With this change, the OpenFaaS CLI tool will be able to pull function
templates from within the Docker container.
Added `git` tool to OpenFaaS CLI Docker image. Without `git`, the CLI tool will not perform functions that require it.
Signed-off-by: James Smith <jamessmithsmusic@gmail.com>
Issue was raised by @alexellis (#448).
Tested with `build.sh`.
```
$ http_proxy=<COMPANY_PROXY> https_proxy=<COMPANY_PROXY> ./build.sh
$ docker run -ti -e http_proxy=<COMPANY_PROXY> -e https_proxy=<COMPANY_PROXY> openfaas/faas-cli:latest-dev faas-cli template pull
```
Also tested with `build_redist.sh`.
```
$ http_proxy=<COMPANY_PROXY> https_proxy=<COMPANY_PROXY> ./build_redist.sh
$ docker run -ti -e http_proxy=<COMPANY_PROXY> -e https_proxy=<COMPANY_PROXY> openfaas/faas-cli:latest-dev faas-cli template …
```

Include `git` in the apk packages of Docker image

---

builder/build.go
builder/exec.go
commands/build.go
commands/deploy.go
commands/push.go

Duplicates [#477](https://github.com/openfaas/faas-cli/pull/447) for test purposes

Generate unique image tag on build

---

builder/build.go
builder/build_test.go
builder/exec.go
commands/build.go
commands/deploy.go
commands/push.go
schema/image.go
schema/image_test.go

Code review and fix-up for --tag feature
```
- Adds --tag=SHA option for build/push/deploy
- Corrects behaviour "tag" was not being honoured from the Docker
tag within the YAML file
- Did not work at all, had major blocking bug causing build to
fail to work by adding -t twice
- Wrote unit tests for new behaviour extracting new methods
- Introduced mode SHA / default and branch - branch-mode is yet to
be implemented
- Added final Docker image name to status updates in build command
- Tested with samples from faas-cli repo using --tag=SHA on/off
```

 Code review and fix-up for --tag feature

---

commands/faas.go
commands/new_function.go
commands/new_function_test.go

Add `latest` tag to new functions created by OpenFaaS CLI tool.
Append `latest` tag to all newly created functions. This fixes a bug
where images being pushed without a tag will update all tags of the
image. Now, only the current tag will be pushed. Fix is implemented with
Golang template to allow for greater flexibility.
Fixes: openfaas/faas#779
Signed-off-by: James Smith <jamessmithsmusic@gmail.com>
References [[#779](https://github.com/openfaas/faas/issues/779)] in [openfaas/faas](https://github.com/openfaas/faas).
Existing tests were ran successfully.
Verified existing functions without a tag are not broken by :
- Creating new function
- removing supplied tag `latest`
- Build / Push function
- Update tag to `v0.0.1`
- Build / Push function
- verify that only tag `v0.0.1` is updated
- …

Add Default Tag to New Functions

---

commands/new_function.go

Makes OPENFAAS_URL if set to be the base .yml function gateway
instead of the defualtURL which is 127.0.0.1:8080
Makes OPENFAAS_URL the default url when making new functions with 
```faas-cli new ...``` if set.
Before the change even if OPENFAAS_URL was set when creating new function the default gateway was the defaultURL - 127.0.0.1:8080 now by default OPENFAAS_URL if set is taken.
Closes #482 .
Create function with ```OPENFAAS_URL``` and ```--gateway``` unset
```
$ faas-cli new fun --lang=go
...
$ cat fun.yml
provider:
name: faas
functions:
fun:
lang: go
handler: ./fun
image: fun:latest
```
Create function with ```OPENFAAS_URL``` set and ```--gateway``` unset
```
$ export OPENFAAS_URL=23
$ faas-cli …
```

Add OPENFAAS_URL as base url for gateway if set

---

commands/deploy.go

Replacing label typo with annotation in case error is returned
from parsing
Fixing label typo with the proper value.
Fixes #500 .

Fix small label typo on returncode

---

Dockerfile
Dockerfile.redist

Uses utility script which is multi-arch meaning we can use
one Dockerfile for varying platforms.

Get license-check via get.sh

---

proxy/invoke.go

Adds support for additional HTTP verbs PATCH, OPTIONS and HEAD
All verbs used with REST APIs are now supported: "GET", "POST", "PUT",
"PATCH", "DELETE", "OPTIONS", "HEAD"
Using a custom build of `faas-gateway`
Note in the output below `Http_Method=PATCH`
```
$ echo | ./faas-cli invoke env-test --method PATCH
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=9fcfbb9b0fd2
fprocess=env
HOME=/root
Http_User_Agent=Go-http-client/1.1
Http_Accept_Encoding=gzip
Http_Content_Type=text/plain
Http_X_Call_Id=462b953a-2cf9-4b03-aa16-b7ff0b05c8ed
Http_X_Forwarded_For=10.255.0.2:37292
Http_X_Start_Time=1534620562357807614
Http_Authorization=Basic YWRtaW46YTZlYzIzNGI1MTM3ZGY0NTU2MGFjNGQ3MTNiNGQyZmFiYmRhOTVhMTQyZWRkM2UwMzc0NmUzOGVmZmUyZjY1ZQ==
Http_Method=PATCH …
```

[WIP] Adds support for additional HTTP verbs PATCH, OPTIONS and HEAD

---

commands/version.go
proxy/version.go

This commit proxies the HTTP calls made in `version` command.
Fixes : #519

Proxy version command HTTP call

---

.travis.yml
Makefile
build_integration_test.sh

Signed-off-by: Ivana Yovcheva (VMware) <iyovcheva@vmware.com>
This change intends to prevent regression in the new CLI releases.
It makes a build using the CLI and tests how running container
from the function image behaves
#527
`make test-integration`
Tested on Ubuntu and Mac OS.
Tested on ARM by @rdimitrov

Add integration test for templating during CI

---

commands/build.go
commands/deploy.go
commands/generate.go
commands/push.go

Tweaks `--tag` help text and code,  removes reference to unused `file` tag option and explicitly lists `sha` and `branch` options in help text.
Local build and visual inspection of help output, along with running build/push with `--tag`

Fix comments and examples for --tag

---

Dockerfile
Dockerfile.redist

Bump version to Go 1.10.4
- references https://github.com/openfaas/faas/issues/875
Tested with build.sh / build_redist.sh

Bump version to Go 1.10.4

---

commands/store_list.go

This PR implements feature request in #540
As stated in the issue, this PR aims to improve UX.
I ran `faas-cli store ls` locally.

Add ls alias to store list

---

commands/describe.go
schema/describe.go

This commit prints labels and annotations in `faas-cli describe` command
whenever it is available.
Fixes: #533
#533 
Tested on local mac.
```
./faas-cli describe github-push  -g http://142.93.39.213:8080/
Name:                github-push
Replicas:            1
Available replicas:  1
Invocations:         15
Image:               viveksyngh/github-push:0.6.1
Function process:    ./handler
URL:                 http://142.93.39.213:8080/function/github-push
Async URL:           http://142.93.39.213:8080/async-function/github-push
Labels:              com.openfaas.function : github-push
com.openfaas.uid : 681105909
function : true
openfaas-cloud : 1
role : openfaas-system
```
```
/faas-cli describe figlet  -g …
```

Print labels and annotations in describe command

---

README.md

Signed-off-by: qinpengfei <qinpengfei@jd.com>
Describe #554 
#

fix link not exist

---

.github/ISSUE_TEMPLATE.md
commands/deploy.go

This change resets the secrets slice on each iteration so that only the secrets associated with a function are mounted into that function.
Also fixed a typo in the github issue template.
* Create multiple functions
```
$ faas new --lang node fn1
Folder: fn1 created.
|_|
Function created in folder: fn1
Stack file written: fn1.yml
Notes:
You have created a new function which uses Node.js 8.9.1.
npm i --save can be used to add third-party packages like request or cheerio
npm documentation: https://docs.npmjs.com/
$ …
```

Make secrets function specific

---

versioncontrol/core.go
versioncontrol/git.go

Prevents users `.gitconfig` setting from altering template file line endings, this can cause function builds to fail when Linux `CRLF` endings are converted to Unix `LF` and vice-versa.
Also fixes an error in the `versioncontrol.core` header comment which I spotted while in there.

Use core.autocrlf false when cloning templates

---

commands/faas.go
commands/login.go
commands/new_function.go
commands/remove.go
proxy/delete.go
proxy/delete_test.go
proxy/deploy.go
proxy/describe.go
proxy/invoke.go
proxy/list.go
proxy/proxy.go
proxy/proxy_test.go
proxy/version.go

The `invoke` command was ignoring the `--tls-no-verify` flag
```
echo "ed" | faas-cli invoke figlet --gateway https://openfaas-1924654068.eu-west-1.elb.amazonaws.com  --tls-no-verify
Post https://openfaas-1924654068.eu-west-1.elb.amazonaws.com/function/figlet: x509: certificate signed by unknown authority
Cannot connect to OpenFaaS on URL: https://openfaas-1924654068.eu-west-1.elb.amazonaws.com
```
Test matrix for `MakeHTTPClient`
| command | done? |
| ------------- | --- |
| store | <ul><li>  [x] </li></ul>         |
| remove | <ul><li>  [x] </li></ul>         |
| deploy |<ul><li>  [x] </li></ul>         | 
| describe | <ul><li>  [x] </li></ul>         |
| invoke | <ul><li>  [x] </li></ul>         |
| list | <ul><li>  [x] </li></ul>         |
| version | <ul><li>  [x] </li></ul> …

Invoke command fix for --tls-no-verify

---

.travis.yml
Dockerfile
Dockerfile.redist

Updates Go version to 1.11 
This is the current version of Golang, but could do with more exploratory testing from the community before merging. @stefanprodan may also have other input having commented about this version and static binaries in the past.
https://github.com/openfaas/faas/issues/875
Unit tests pass and ran some exploratory tested with
build_redist.sh and binaries used on MacOS, Arch Linux (x86_64)
and Raspbian (armhf).

Update Go version to 1.11

---

Makefile

Signed-off-by: Radoslav Dimitrov <rdimitrow@gmail.com>

Add consistent ARM64 build image process

---

Makefile

Signed-off-by: Radoslav Dimitrov <rdimitrow@gmail.com>
Refactor the usage of .PHONY targets

Refactor .PHONY

---

commands/secret_create.go
commands/secret_create_test.go
commands/secret_remove.go
commands/secret_remove_test.go
commands/secret_update.go
commands/secret_update_test.go
proxy/secret.go

Goal: add secret update command.
Signed-off-by: Leonardo Di Donato <leodidonato@gmail.com>
Adds update secrets command.
Contributes to #577

Add faas secret update command

---

README.md

Signed-off-by: Rajat Jindal <rajatjindal83@gmail.com>
Change documentation to add link to openfaas-cloud pub-cert.pem

Add link to openfaas-cloud pub-cert.pem

---

commands/deploy.go
commands/errors.go
commands/errors_test.go
commands/secret_create.go
commands/secret_list.go
commands/secret_remove.go
commands/secret_update.go
proxy/deploy.go
proxy/secret.go

Proxy TLS warnings refactoring
I have made all the TLS warnings from the proxy pkg to the commands. pkg
Having the TLS checks in the proxy made it more difficult to reuse. So having the TLS checks on the client is more flexible. Also there was some code duplicating we could simplify
fixes #581 
- [x ] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))
deploy 
```
Deploying: hello-fork.
URL: http://127.0.0.1:8080/function/hello-fork
```
list
```
$ faas-cli secret ls …
```

Proxy TLS warnings refactoring

---

commands/store_deploy.go

Signed-off-by: Mario Mazo <buster.mazo@gmail.com>
Skip tls verification was not available in the store deploy
Now we just read the flag from the command line
fixes #594 
before
```
$ faas-cli store deploy  figlet --tls-no-verify
Unknown flag: --tls-no-verify
```
after
```
$ faas-cli store deploy figlet --tls-no-verify
URL: http://127.0.0.1:8080/function/figlet
```

Added --tls-no-verify to store deploy

---

README.md

Signed-off-by: Andrew Urwin <ellieniwru@hotmail.co.uk>
Correcting several typos and grammar issues in readme.md file
Removes several typos and errors from readme file of faas-cli
Documentation - no testing but requires verification
Documentation

correcting typos in readme file

---

README.md
commands/login.go
commands/new_function.go
commands/new_function_test.go
commands/store_list.go

Update "faas-cli new" help message 
- when neither the name nor the language is given, then show the
help message to the user
- updated --list flag to instruct users on how to get templates
including from the store
- update README file to add `faas-cli up` as listed command
Improve UX
Tested on MacOS with local build. Unit tests updated.

Update "faas-cli new" help message

---

commands/cloud.go

Signed-off-by: Matias Pan <matias.pan26@gmail.com>
This PR fixes the following typo: `namepsace`
No need to test.

Fix namespace typo

---

builder/build_test.go

This commit fixes issue with unit tests in builder package.
Fixes: #622
#622 
Since it is only unit tests update .. No need to test the functionalities.

Fix unit test for builder

---

proxy/secret_test.go

Add unit test cases for secrets proxy

---

commands/generate.go
schema/metadata.go
schema/openfaas/v1alpha2/crd.go

This commit refactor openfaas crd schema puts it inside a package with
a version name so that it's easy to add new version for openfaas CRD
```
./faas-cli generate crd
---
apiVersion: openfaas.com/v1alpha2
kind: Function
metadata:
name: url-ping
namespace: openfaas-fn
spec:
name: url-ping
image: alexellis/faas-url-ping:0.2
---
apiVersion: openfaas.com/v1alpha2
kind: Function
metadata:
name: stronghash
namespace: openfaas-fn
spec:
name: stronghash
image: functions/alpine:latest
---
apiVersion: openfaas.com/v1alpha2
kind: Function
metadata:
name: nodejs-echo
namespace: openfaas-fn
spec:
name: nodejs-echo
image: alexellis/faas-nodejs-echo:0.1
---
apiVersion: openfaas.com/v1alpha2
kind: Function
metadata:
name: shrink-image
namespace: …
```

Refactor openfaas crd generation

---

commands/generate.go

Update generate CRD command help message

---

commands/logs.go

Tested on local. 
Before. 
```
faas-cli logs                                                    
Accepts 1 arg(s), received 0
```
Now. 
```
./faas-cli logs 
Function name is required
./faas-cli logs abc def 
Accepts at most 1 arg(s), received 2
```

Improve error message for missing function name

---

commands/deploy.go

Signed-off-by: Bruno Miguel Custódio <brunomcustodio@gmail.com>
`faas deploy` requires the function's template to be present even if the image has been pre-built. This PR adds a `--no-read-template` flag that, if set, will bypass reading the template altogether.
( I haven't raised an issue, but I've previously discussed this with @alexellis—this was actually his suggestion :) ).
By compiling `faas-cli` and running `faas-cli deploy` without the template directory being present.
```
➜  test-fn git:(master) ✗ ls -lah stack.yml
-rw-r--r--  1 bmcstdio  staff   872B Aug 15 13:23 stack.yml
➜  test-fn git:(master) ✗ ls -lah template
ls: template: No such file or directory
➜  test-fn git:(master) ✗ ./faas-cli deploy
Deploying: test-fn.
Template directory may be missing or invalid, please run …
```

Add a '--no-read-template' flag to 'faas deploy'.

---

proxy/secret_test.go

Add unit test for secrets in forbidden namespace

---

commands/remove.go
commands/remove_test.go

Signed-off-by: Rene Kaufmann <kaufmann.r@gmail.com>
This should fix issue #280 
We only need to parse the yaml file if no function name is specified.

Update commands to prefer named functions over yaml files

---

npm/README.md
npm/install-test.js
npm/install.js
npm/lib.js
npm/package.json
npm/test.js

Add tests for npm install script
This change relates only to the npm install script
It rearranges the script in order to make the individual
functions testable without affecting the actual installation.
Added unit tests for each of the cases in the getSuffix function
to ensure that the results will remain as expected.
No testing framework dependency is used in an effort to reduce
the size of the installation as the faas-cli uses the npm 
installation process and we don't want to pull more dependencies
than absolutely necessary
Tested by running the tests :)
Output:
```sh
> @openfaas/faas-cli@0.9.3 test /home/burtonr/code/go/src/github.com/openfaas/faas-cli/npm
> node test.js
Test Suite: SuffixTests
Windows ✔
LinuxX64 ✔
LinuxArm64 ✔
LinuxArmhf6 ✔
LinuxArmhf7 ✔
MacOS ✔
Unsupported ✔
Test …
```

Npm install updates

---

commands/logout.go

Fixes #762 
I have tested on my local system.
```
./faas-cli logout
Gateway http://127.0.0.1:8080 not found in config
➜  faas-cli git:(master) ✗ export OPENFAAS_URL=http://127.0.0.1:31112
➜  faas-cli git:(master) ✗ ./faas-cli logout
credentials removed for http://127.0.0.1:31112
```

Read gateway environment in logout command

---

commands/deploy.go
commands/describe.go
commands/general.go
commands/list.go
commands/logs.go
commands/namespaces.go
commands/remove.go
commands/secret_create.go
commands/secret_list.go
commands/secret_remove.go
commands/secret_update.go
commands/store_deploy.go
commands/version.go
config/auth.go
proxy/auth.go
proxy/client.go
proxy/client_test.go
proxy/delete_test.go
proxy/deploy_test.go
proxy/describe_test.go
proxy/list_test.go
proxy/logs_test.go
proxy/secret_test.go

Fixes: #797 
I have tested this on my mac with local openfaas deployment.

Move cli authentication to config package

---

.travis.yml
Dockerfile
Makefile
build.sh

Adds a root user to DockerImage for the CI flow so the faas-cli root docker image can be used with CI/CD platforms like Google Cloud Build, check out #804 for detailed findings of what this PR will bring.
Issue #809 
Check it out here in the [comment](https://github.com/openfaas/faas-cli/pull/813#issuecomment-644630868)

Add root user to Dockerfile for Google Cloud Build

---

commands/generate.go
schema/knative/v1alpha1/serving.go
schema/metadata.go

Add annotations to revisionTemplate for knative
* Adds metadata to the knative spec in the generation command
* Fixes: #815
```
Tested by running locally and verifying it matched the request
from @Jeff-Lowrey
faas-cli generate \
--api=serving.knative.dev/v1alpha1 \
--annotation sidecar.istio.io/inject=true
This also works when bringing in annotations from the YAML
file.
```

Add annotations to revisionTemplate for knative

---

commands/generate.go
go.mod
schema/knative/v1alpha1/serving.go
stack.yml

Fix #829 to fix Knative spec generation
Fixes #829 
```bash
./faas-cli generate --filter url-ping -f stack.yml --tag=sha --api serving.knative.dev/v1alpha1
---
apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
name: url-ping
namespace: openfaas-fn
spec:
runLatest:
configuration:
revisionTemplate:
spec:
container:
image: alexellis/faas-url-ping:0.2-c12d57c
```

Fix #829 to fix Knative spec generation

---

commands/generate.go
commands/generate_test.go
schema/knative/v1/serving.go
schema/openfaas/v1alpha2/crd.go

Update alpha namespaces to v1
This should have been done before, but was missed.
CI

Update alpha namespaces to v1

---

guide/TEMPLATE.md

I found a mistake in the template overwrite command.
Should I raise an issue for typo fix?
In this PR, I'm only making changes to the documentation. Therefore, no testing is required.

docs: fix overwrite command

---

commands/login.go

Add timeout option for login command
Fixes: #862 where a user ran into a timeout due to networking
issues where it passed some of the time when it took 4s.
Tested by setting the timeout to 1ms and seeing it fail, then
upping the value to 10ms and seeing it work. Default seems
sensible at 5s, so leaving as is for now.

Add timeout option for login command

---

Dockerfile
Dockerfile.redist
sample/imagemagick/Dockerfile

Signed-off-by: Gábor Lipták <gliptak@gmail.com>

Bump alpine to 3.13

---

commands/describe.go
go.mod
go.sum
proxy/client.go
proxy/describe.go
proxy/describe_test.go
proxy/list.go
schema/describe.go
vendor/github.com/openfaas/faas-provider/types/function_deployment.go
vendor/github.com/openfaas/faas-provider/types/function_status.go
vendor/github.com/openfaas/faas-provider/types/queue.go
vendor/github.com/openfaas/faas-provider/types/secret.go
vendor/modules.txt

Add usage metrics for describe command
As part of adding CPU/RAM metrics per function, this PR shows the data up in the describe command.
```bash
go build && ./faas-cli describe cows5 -n dev
Name:                cows5
Replicas:            9
Available replicas:  9
Invocations:         27000
Image:               ghcr.io/openfaas/cows:latest
Function process:    
URL:                 http://127.0.0.1:8080/function/cows5.dev
Async URL:           http://127.0.0.1:8080/async-function/cows5.dev
Labels               faas_function : cows5
Annotations          prometheus.io.scrape : false
RAM:                 224.07 MB
CPU:                 4 Mi
```
Negative test case with faasd:
```bash
go build && ./faas-cli …
```

Add usage metrics for describe command

---

.gitignore
Dockerfile.redist
Makefile
build_integration_test.sh
extract_binaries.sh

Signed-off-by: Nitishkumar Singh <nitishkumarsingh71@gmail.com>
Provide cli support for `arm64` architecture on `darwin` i.e. mac os
Closes #941 
1. Run `Dockerfile.redist`
```
docker build -f ./Dockerfile.redist -t openfaas/faas-cli:latest-dev .
```
2. Extract binaries using `extract_binaries.sh`
3. check `bin` folder for `faas-cli-darwin-arm64`

Add support for arm64 architecture on darwin
